const PRICING_REFERENCE_VERSION = '2026-04-24-zone-rebalance-v2';

const ZONES = [
  { slug: 'zone-1', name: 'Zone 1 — Premium markets',          multiplier: '1.0000', sortOrder: 1 },
  { slug: 'zone-2', name: 'Zone 2 — Mid-tier developed',       multiplier: '0.8500', sortOrder: 2 },
  { slug: 'zone-3', name: 'Zone 3 — Emerging markets',         multiplier: '0.6500', sortOrder: 3 },
  { slug: 'zone-4', name: 'Zone 4 — Price-sensitive emerging', multiplier: '0.5000', sortOrder: 4 },
];

// Format: [countryCode, countryName, region, currencyCode, currencySymbol, zoneSlug]
const COUNTRIES = [
  ['US', 'United States',    'North America', 'USD', '$',    'zone-1'],
  ['CA', 'Canada',           'North America', 'CAD', 'C$',   'zone-1'],
  ['GB', 'United Kingdom',   'Europe',        'GBP', '£',    'zone-1'],
  ['IE', 'Ireland',          'Europe',        'EUR', '€',    'zone-1'],
  ['AU', 'Australia',        'Oceania',       'AUD', 'A$',   'zone-1'],
  ['NZ', 'New Zealand',      'Oceania',       'NZD', 'NZ$',  'zone-1'],
  ['SG', 'Singapore',        'Asia',          'SGD', 'S$',   'zone-1'],
  ['HK', 'Hong Kong',        'Asia',          'HKD', 'HK$',  'zone-1'],
  ['CH', 'Switzerland',      'Europe',        'CHF', 'Fr.',  'zone-1'],
  ['NO', 'Norway',           'Europe',        'NOK', 'kr',   'zone-1'],
  ['DK', 'Denmark',          'Europe',        'DKK', 'kr',   'zone-1'],
  ['SE', 'Sweden',           'Europe',        'SEK', 'kr',   'zone-1'],
  ['FI', 'Finland',          'Europe',        'EUR', '€',    'zone-1'],
  ['NL', 'Netherlands',      'Europe',        'EUR', '€',    'zone-1'],
  ['DE', 'Germany',          'Europe',        'EUR', '€',    'zone-1'],
  ['FR', 'France',           'Europe',        'EUR', '€',    'zone-1'],
  ['BE', 'Belgium',          'Europe',        'EUR', '€',    'zone-1'],
  ['AT', 'Austria',          'Europe',        'EUR', '€',    'zone-1'],
  ['LU', 'Luxembourg',       'Europe',        'EUR', '€',    'zone-1'],
  ['IS', 'Iceland',          'Europe',        'ISK', 'kr',   'zone-1'],
  ['IL', 'Israel',           'Middle East',   'ILS', '₪',    'zone-2'],
  ['AE', 'United Arab Emirates', 'Middle East', 'AED', 'AED ', 'zone-1'],
  ['QA', 'Qatar',            'Middle East',   'QAR', 'QAR ', 'zone-1'],

  ['ES', 'Spain',            'Europe',        'EUR', '€',    'zone-2'],
  ['IT', 'Italy',            'Europe',        'EUR', '€',    'zone-2'],
  ['PT', 'Portugal',         'Europe',        'EUR', '€',    'zone-2'],
  ['GR', 'Greece',           'Europe',        'EUR', '€',    'zone-2'],
  ['CZ', 'Czech Republic',   'Europe',        'CZK', 'Kč',   'zone-2'],
  ['PL', 'Poland',           'Europe',        'PLN', 'zł',   'zone-2'],
  ['SK', 'Slovakia',         'Europe',        'EUR', '€',    'zone-2'],
  ['SI', 'Slovenia',         'Europe',        'EUR', '€',    'zone-2'],
  ['EE', 'Estonia',          'Europe',        'EUR', '€',    'zone-2'],
  ['LT', 'Lithuania',        'Europe',        'EUR', '€',    'zone-2'],
  ['LV', 'Latvia',           'Europe',        'EUR', '€',    'zone-2'],
  ['CY', 'Cyprus',           'Europe',        'EUR', '€',    'zone-2'],
  ['MT', 'Malta',            'Europe',        'EUR', '€',    'zone-2'],
  ['KR', 'South Korea',      'Asia',          'KRW', '₩',    'zone-2'],
  ['JP', 'Japan',            'Asia',          'JPY', '¥',    'zone-2'],
  ['TW', 'Taiwan',           'Asia',          'TWD', 'NT$',  'zone-2'],
  ['SA', 'Saudi Arabia',     'Middle East',   'SAR', 'SAR ', 'zone-2'],
  ['KW', 'Kuwait',           'Middle East',   'KWD', 'KWD ', 'zone-2'],
  ['BH', 'Bahrain',          'Middle East',   'BHD', 'BHD ', 'zone-2'],
  ['OM', 'Oman',             'Middle East',   'OMR', 'OMR ', 'zone-2'],

  ['BR', 'Brazil',           'South America', 'BRL', 'R$',   'zone-3'],
  ['MX', 'Mexico',           'North America', 'MXN', 'MX$',  'zone-3'],
  ['AR', 'Argentina',        'South America', 'ARS', 'AR$',  'zone-3'],
  ['CL', 'Chile',            'South America', 'CLP', 'CL$',  'zone-3'],
  ['CO', 'Colombia',         'South America', 'COP', 'COL$', 'zone-3'],
  ['PE', 'Peru',             'South America', 'PEN', 'S/',   'zone-3'],
  ['UY', 'Uruguay',          'South America', 'UYU', '$U',   'zone-3'],
  ['CR', 'Costa Rica',       'North America', 'CRC', '₡',    'zone-3'],
  ['PA', 'Panama',           'North America', 'USD', '$',    'zone-3'],
  ['ZA', 'South Africa',     'Africa',        'ZAR', 'R',    'zone-3'],
  ['TR', 'Turkey',           'Europe',        'TRY', '₺',    'zone-3'],
  ['RO', 'Romania',          'Europe',        'RON', 'lei',  'zone-3'],
  ['BG', 'Bulgaria',         'Europe',        'BGN', 'лв',   'zone-3'],
  ['HU', 'Hungary',          'Europe',        'HUF', 'Ft',   'zone-2'],
  ['HR', 'Croatia',          'Europe',        'EUR', '€',    'zone-3'],
  ['RS', 'Serbia',           'Europe',        'RSD', 'РСД',  'zone-3'],
  ['UA', 'Ukraine',          'Europe',        'UAH', '₴',    'zone-4'],
  ['MY', 'Malaysia',         'Asia',          'MYR', 'RM',   'zone-3'],
  ['TH', 'Thailand',         'Asia',          'THB', '฿',    'zone-3'],
  ['PH', 'Philippines',      'Asia',          'PHP', '₱',    'zone-4'],
  ['VN', 'Vietnam',          'Asia',          'VND', '₫',    'zone-4'],
  ['ID', 'Indonesia',        'Asia',          'IDR', 'Rp',   'zone-4'],
  ['CN', 'China',            'Asia',          'CNY', '¥',    'zone-3'],
  ['RU', 'Russia',           'Europe',        'RUB', '₽',    'zone-3'],

  ['IN', 'India',            'Asia',          'INR', '₹',    'zone-4'],
  ['PK', 'Pakistan',         'Asia',          'PKR', '₨',    'zone-4'],
  ['BD', 'Bangladesh',       'Asia',          'BDT', '৳',    'zone-4'],
  ['LK', 'Sri Lanka',        'Asia',          'LKR', 'Rs',   'zone-4'],
  ['NP', 'Nepal',            'Asia',          'NPR', 'Rs',   'zone-4'],
  ['BT', 'Bhutan',           'Asia',          'BTN', 'Nu.',  'zone-4'],
  ['MM', 'Myanmar',          'Asia',          'MMK', 'K',    'zone-4'],
  ['KH', 'Cambodia',         'Asia',          'KHR', '៛',    'zone-4'],
  ['LA', 'Laos',             'Asia',          'LAK', '₭',    'zone-4'],
  ['NG', 'Nigeria',          'Africa',        'NGN', '₦',    'zone-4'],
  ['KE', 'Kenya',            'Africa',        'KES', 'KSh',  'zone-4'],
  ['GH', 'Ghana',            'Africa',        'GHS', '₵',    'zone-4'],
  ['EG', 'Egypt',            'Africa',        'EGP', 'E£',   'zone-4'],
  ['MA', 'Morocco',          'Africa',        'MAD', 'MAD ', 'zone-4'],
  ['TN', 'Tunisia',          'Africa',        'TND', 'TND ', 'zone-4'],
  ['DZ', 'Algeria',          'Africa',        'DZD', 'DZD ', 'zone-4'],
  ['ET', 'Ethiopia',         'Africa',        'ETB', 'Br',   'zone-4'],
  ['TZ', 'Tanzania',         'Africa',        'TZS', 'TSh',  'zone-4'],
  ['UG', 'Uganda',           'Africa',        'UGX', 'USh',  'zone-4'],
  ['RW', 'Rwanda',           'Africa',        'RWF', 'FRw',  'zone-4'],
  ['SN', 'Senegal',          'Africa',        'XOF', 'CFA',  'zone-4'],
  ['CI', "Côte d'Ivoire",    'Africa',        'XOF', 'CFA',  'zone-4'],

  ['AD', 'Andorra',          'Europe',        'EUR', '€',    'zone-2'],
  ['AL', 'Albania',          'Europe',        'ALL', 'L',    'zone-3'],
  ['BA', 'Bosnia and Herzegovina', 'Europe',  'BAM', 'KM',   'zone-3'],
  ['BY', 'Belarus',          'Europe',        'BYN', 'Br',   'zone-3'],
  ['FO', 'Faroe Islands',    'Europe',        'DKK', 'kr',   'zone-2'],
  ['GG', 'Guernsey',         'Europe',        'GBP', '£',    'zone-2'],
  ['GI', 'Gibraltar',        'Europe',        'GIP', '£',    'zone-2'],
  ['GL', 'Greenland',        'Europe',        'DKK', 'kr',   'zone-2'],
  ['IM', 'Isle of Man',      'Europe',        'GBP', '£',    'zone-2'],
  ['JE', 'Jersey',           'Europe',        'GBP', '£',    'zone-2'],
  ['LI', 'Liechtenstein',    'Europe',        'CHF', 'Fr.',  'zone-1'],
  ['MC', 'Monaco',           'Europe',        'EUR', '€',    'zone-1'],
  ['MD', 'Moldova',          'Europe',        'MDL', 'L',    'zone-3'],
  ['ME', 'Montenegro',       'Europe',        'EUR', '€',    'zone-3'],
  ['MK', 'North Macedonia',  'Europe',        'MKD', 'ден',  'zone-3'],
  ['SM', 'San Marino',       'Europe',        'EUR', '€',    'zone-2'],
  ['VA', 'Vatican City',     'Europe',        'EUR', '€',    'zone-2'],
  ['XK', 'Kosovo',           'Europe',        'EUR', '€',    'zone-3'],

  ['AF', 'Afghanistan',      'Asia',          'AFN', '؋',    'zone-4'],
  ['AM', 'Armenia',          'Asia',          'AMD', '֏',    'zone-3'],
  ['AZ', 'Azerbaijan',       'Asia',          'AZN', '₼',    'zone-3'],
  ['BN', 'Brunei',           'Asia',          'BND', 'B$',   'zone-2'],
  ['GE', 'Georgia',          'Asia',          'GEL', '₾',    'zone-3'],
  ['IQ', 'Iraq',             'Middle East',   'IQD', 'IQD ', 'zone-3'],
  ['IR', 'Iran',             'Middle East',   'IRR', 'IRR ', 'zone-3'],
  ['JO', 'Jordan',           'Middle East',   'JOD', 'JOD ', 'zone-4'],
  ['KG', 'Kyrgyzstan',       'Asia',          'KGS', 'с',    'zone-4'],
  ['KP', 'North Korea',      'Asia',          'KPW', '₩',    'zone-4'],
  ['KZ', 'Kazakhstan',       'Asia',          'KZT', '₸',    'zone-3'],
  ['LB', 'Lebanon',          'Middle East',   'LBP', 'LBP ', 'zone-4'],
  ['MN', 'Mongolia',         'Asia',          'MNT', '₮',    'zone-3'],
  ['MV', 'Maldives',         'Asia',          'MVR', 'Rf',   'zone-3'],
  ['PS', 'Palestine',        'Middle East',   'ILS', '₪',    'zone-4'],
  ['SY', 'Syria',            'Middle East',   'SYP', '£S',   'zone-4'],
  ['TJ', 'Tajikistan',       'Asia',          'TJS', 'SM',   'zone-4'],
  ['TL', 'Timor-Leste',      'Asia',          'USD', '$',    'zone-4'],
  ['TM', 'Turkmenistan',     'Asia',          'TMT', 'm',    'zone-3'],
  ['UZ', 'Uzbekistan',       'Asia',          'UZS', 'soʻm', 'zone-4'],
  ['YE', 'Yemen',            'Middle East',   'YER', 'YER ', 'zone-4'],

  ['AO', 'Angola',           'Africa',        'AOA', 'Kz',   'zone-4'],
  ['BF', 'Burkina Faso',     'Africa',        'XOF', 'CFA',  'zone-4'],
  ['BI', 'Burundi',          'Africa',        'BIF', 'FBu',  'zone-4'],
  ['BJ', 'Benin',            'Africa',        'XOF', 'CFA',  'zone-4'],
  ['BW', 'Botswana',         'Africa',        'BWP', 'P',    'zone-3'],
  ['CD', 'Congo (DRC)',      'Africa',        'CDF', 'FC',   'zone-4'],
  ['CF', 'Central African Republic', 'Africa', 'XAF', 'FCFA', 'zone-4'],
  ['CG', 'Congo (Republic)', 'Africa',        'XAF', 'FCFA', 'zone-4'],
  ['CM', 'Cameroon',         'Africa',        'XAF', 'FCFA', 'zone-4'],
  ['CV', 'Cape Verde',       'Africa',        'CVE', '$',    'zone-4'],
  ['DJ', 'Djibouti',         'Africa',        'DJF', 'Fdj',  'zone-4'],
  ['ER', 'Eritrea',          'Africa',        'ERN', 'Nfk',  'zone-4'],
  ['GA', 'Gabon',            'Africa',        'XAF', 'FCFA', 'zone-3'],
  ['GM', 'Gambia',           'Africa',        'GMD', 'D',    'zone-4'],
  ['GN', 'Guinea',           'Africa',        'GNF', 'FG',   'zone-4'],
  ['GQ', 'Equatorial Guinea','Africa',        'XAF', 'FCFA', 'zone-3'],
  ['GW', 'Guinea-Bissau',    'Africa',        'XOF', 'CFA',  'zone-4'],
  ['KM', 'Comoros',          'Africa',        'KMF', 'CF',   'zone-4'],
  ['LR', 'Liberia',          'Africa',        'LRD', 'L$',   'zone-4'],
  ['LS', 'Lesotho',          'Africa',        'LSL', 'L',    'zone-4'],
  ['LY', 'Libya',            'Africa',        'LYD', 'LYD ', 'zone-3'],
  ['MG', 'Madagascar',       'Africa',        'MGA', 'Ar',   'zone-4'],
  ['ML', 'Mali',             'Africa',        'XOF', 'CFA',  'zone-4'],
  ['MR', 'Mauritania',       'Africa',        'MRU', 'UM',   'zone-4'],
  ['MU', 'Mauritius',        'Africa',        'MUR', 'Rs',   'zone-3'],
  ['MW', 'Malawi',           'Africa',        'MWK', 'MK',   'zone-4'],
  ['MZ', 'Mozambique',       'Africa',        'MZN', 'MT',   'zone-4'],
  ['NA', 'Namibia',          'Africa',        'NAD', 'N$',   'zone-3'],
  ['NE', 'Niger',            'Africa',        'XOF', 'CFA',  'zone-4'],
  ['SC', 'Seychelles',       'Africa',        'SCR', 'SR',   'zone-3'],
  ['SD', 'Sudan',            'Africa',        'SDG', '£S',   'zone-4'],
  ['SL', 'Sierra Leone',     'Africa',        'SLL', 'Le',   'zone-4'],
  ['SO', 'Somalia',          'Africa',        'SOS', 'S',    'zone-4'],
  ['SS', 'South Sudan',      'Africa',        'SSP', 'SS£',  'zone-4'],
  ['ST', 'São Tomé and Príncipe', 'Africa',   'STN', 'Db',   'zone-4'],
  ['SZ', 'Eswatini',         'Africa',        'SZL', 'E',    'zone-4'],
  ['TD', 'Chad',             'Africa',        'XAF', 'FCFA', 'zone-4'],
  ['TG', 'Togo',             'Africa',        'XOF', 'CFA',  'zone-4'],
  ['ZM', 'Zambia',           'Africa',        'ZMW', 'ZK',   'zone-4'],
  ['ZW', 'Zimbabwe',         'Africa',        'ZWL', 'Z$',   'zone-4'],

  ['AG', 'Antigua and Barbuda', 'North America', 'XCD', 'EC$',  'zone-3'],
  ['AI', 'Anguilla',         'North America', 'XCD', 'EC$',  'zone-3'],
  ['AW', 'Aruba',            'North America', 'AWG', 'ƒ',    'zone-3'],
  ['BB', 'Barbados',         'North America', 'BBD', 'Bds$', 'zone-3'],
  ['BM', 'Bermuda',          'North America', 'BMD', 'BD$',  'zone-3'],
  ['BO', 'Bolivia',          'South America', 'BOB', 'Bs.',  'zone-4'],
  ['BS', 'Bahamas',          'North America', 'BSD', 'B$',   'zone-3'],
  ['BZ', 'Belize',           'North America', 'BZD', 'BZ$',  'zone-3'],
  ['CU', 'Cuba',             'North America', 'CUP', '₱',    'zone-3'],
  ['CW', 'Curaçao',          'North America', 'ANG', 'ƒ',    'zone-3'],
  ['DM', 'Dominica',         'North America', 'XCD', 'EC$',  'zone-3'],
  ['DO', 'Dominican Republic', 'North America', 'DOP', 'RD$', 'zone-3'],
  ['EC', 'Ecuador',          'South America', 'USD', '$',    'zone-3'],
  ['FK', 'Falkland Islands', 'South America', 'FKP', '£',    'zone-3'],
  ['GD', 'Grenada',          'North America', 'XCD', 'EC$',  'zone-3'],
  ['GF', 'French Guiana',    'South America', 'EUR', '€',    'zone-3'],
  ['GP', 'Guadeloupe',       'North America', 'EUR', '€',    'zone-3'],
  ['GT', 'Guatemala',        'North America', 'GTQ', 'Q',    'zone-3'],
  ['GY', 'Guyana',           'South America', 'GYD', 'G$',   'zone-3'],
  ['HN', 'Honduras',         'North America', 'HNL', 'L',    'zone-4'],
  ['HT', 'Haiti',            'North America', 'HTG', 'G',    'zone-4'],
  ['JM', 'Jamaica',          'North America', 'JMD', 'J$',   'zone-3'],
  ['KN', 'Saint Kitts and Nevis', 'North America', 'XCD', 'EC$', 'zone-3'],
  ['KY', 'Cayman Islands',   'North America', 'KYD', 'CI$',  'zone-3'],
  ['LC', 'Saint Lucia',      'North America', 'XCD', 'EC$',  'zone-3'],
  ['MQ', 'Martinique',       'North America', 'EUR', '€',    'zone-3'],
  ['MS', 'Montserrat',       'North America', 'XCD', 'EC$',  'zone-3'],
  ['NI', 'Nicaragua',        'North America', 'NIO', 'C$',   'zone-4'],
  ['PR', 'Puerto Rico',      'North America', 'USD', '$',    'zone-3'],
  ['PY', 'Paraguay',         'South America', 'PYG', '₲',    'zone-3'],
  ['SR', 'Suriname',         'South America', 'SRD', '$',    'zone-3'],
  ['SV', 'El Salvador',      'North America', 'USD', '$',    'zone-3'],
  ['TC', 'Turks and Caicos', 'North America', 'USD', '$',    'zone-3'],
  ['TT', 'Trinidad and Tobago', 'North America', 'TTD', 'TT$', 'zone-3'],
  ['VC', 'Saint Vincent and the Grenadines', 'North America', 'XCD', 'EC$', 'zone-3'],
  ['VE', 'Venezuela',        'South America', 'VES', 'Bs.',  'zone-4'],
  ['VG', 'British Virgin Islands', 'North America', 'USD', '$', 'zone-3'],
  ['VI', 'U.S. Virgin Islands', 'North America', 'USD', '$', 'zone-3'],

  ['AS', 'American Samoa',   'Oceania',       'USD', '$',    'zone-3'],
  ['CK', 'Cook Islands',     'Oceania',       'NZD', 'NZ$',  'zone-3'],
  ['FJ', 'Fiji',             'Oceania',       'FJD', 'FJ$',  'zone-3'],
  ['FM', 'Micronesia',       'Oceania',       'USD', '$',    'zone-4'],
  ['GU', 'Guam',             'Oceania',       'USD', '$',    'zone-3'],
  ['KI', 'Kiribati',         'Oceania',       'AUD', 'A$',   'zone-4'],
  ['MH', 'Marshall Islands', 'Oceania',       'USD', '$',    'zone-4'],
  ['MP', 'Northern Mariana Islands', 'Oceania', 'USD', '$',  'zone-3'],
  ['NC', 'New Caledonia',    'Oceania',       'XPF', 'F',    'zone-3'],
  ['NR', 'Nauru',            'Oceania',       'AUD', 'A$',   'zone-3'],
  ['NU', 'Niue',             'Oceania',       'NZD', 'NZ$',  'zone-4'],
  ['PF', 'French Polynesia', 'Oceania',       'XPF', 'F',    'zone-3'],
  ['PG', 'Papua New Guinea', 'Oceania',       'PGK', 'K',    'zone-4'],
  ['PW', 'Palau',            'Oceania',       'USD', '$',    'zone-3'],
  ['SB', 'Solomon Islands',  'Oceania',       'SBD', 'SI$',  'zone-4'],
  ['TO', 'Tonga',            'Oceania',       'TOP', 'T$',   'zone-4'],
  ['TV', 'Tuvalu',           'Oceania',       'AUD', 'A$',   'zone-4'],
  ['VU', 'Vanuatu',          'Oceania',       'VUV', 'Vt',   'zone-4'],
  ['WF', 'Wallis and Futuna','Oceania',       'XPF', 'F',    'zone-4'],
  ['WS', 'Samoa',            'Oceania',       'WST', 'T',    'zone-4'],
];

module.exports = {
  PRICING_REFERENCE_VERSION,
  ZONES,
  COUNTRIES,
};
