'use strict';

// Render-time heal for stale theme copy on existing tenants.
//
// When a tenant picks a web theme, buildThemeContentResetPatch() snapshots the
// theme's default copy into BusinessContent. Later improvements to the theme
// default never reach those rows, so existing sites keep the old, bloated copy.
//
// healThemeCopy() swaps a saved field for its improved version ONLY when the
// saved value is byte-for-byte one of the known old machine-generated defaults
// (see themeCopyHealMap.json, generated by scripts/build-theme-copy-heal-map.js).
// Anything the owner actually typed will not match the map and is left exactly
// as-is — so genuine edits are never overwritten. No DB writes; the resolve
// response is healed on the way out.

const HEAL_MAP = require('./themeCopyHealMap.json');

// Storefront-managed copy fields. Mirrors the frontend scrub's managed list.
const MANAGED_FIELDS = [
  'heroHeadline', 'heroSubheading', 'tagline',
  'servicesEyebrow', 'servicesTitle', 'servicesIntro',
  'aboutEyebrow', 'aboutTitle', 'aboutBody',
  'testimonialsEyebrow', 'testimonialsTitle',
  'faqEyebrow', 'faqTitle',
  'contactTitle', 'contactBody', 'contactCardTitle', 'contactCardBody',
  'pricingEyebrow', 'pricingTitle',
  'ctaHeadline', 'ctaBody',
];

function healThemeCopy(content) {
  if (!content || typeof content !== 'object') return content;
  let next = content;
  let cloned = false;
  for (const field of MANAGED_FIELDS) {
    const value = content[field];
    if (typeof value !== 'string') continue;
    const improved = HEAL_MAP[value];
    if (improved === undefined || improved === value) continue;
    if (!cloned) { next = { ...content }; cloned = true; }
    next[field] = improved;
  }
  return next;
}

module.exports = { healThemeCopy, MANAGED_FIELDS };
