const DEFAULT_SECTIONS = {
  services: { label: null, desc: 'Cards showing your services', defaultOn: true },
  about: { label: 'About', desc: 'The story, positioning, and proof points', defaultOn: true },
  team: { label: null, desc: 'People, providers, or featured team members', defaultOn: true },
  gallery: { label: 'Gallery', desc: 'Space, work, or people - 4-12 images', defaultOn: false },
  testimonials: { label: 'Testimonials', desc: 'Customer reviews with star ratings', defaultOn: true },
  pricing: { label: 'Pricing', desc: 'Plan, package, or offer comparison cards', defaultOn: true },
  faq: { label: 'FAQ', desc: 'Pre-empt common questions', defaultOn: false },
  locations: { label: 'Locations', desc: 'Branch addresses from your Locations tab', defaultOn: false },
  contact: { label: 'Contact', desc: 'Contact information and enquiry form', defaultOn: true },
};

const PROFILE_DEFAULTS = {
  businessLabel: 'Business details',
  ctaLabel: null,
  heroLine3Placeholder: 'Tell visitors what makes your work different.',
  trustBadgesHint: 'Three short phrases shown below the CTA. Leave any box empty to use the theme default for that slot. Toggle off to hide all three.',
  servicesSectionTitle: null,
  servicesSectionDesc: null,
  servicesEyebrowPlaceholder: null,
  servicesTitlePlaceholder: 'What We Offer',
  serviceCardsTitle: null,
  serviceCardsHelp: null,
  serviceCardSingular: null,
  serviceCardNamePlaceholder: 'Service name',
  serviceCardDescriptionPlaceholder: 'Short description',
  serviceCardPriceCaptionPlaceholder: 'from',
  serviceCardPricePlaceholder: 'Price',
  serviceCardDurationPlaceholder: '30 min',
  serviceCardFeaturesPlaceholder: 'Bullet features, one per line - optional',
  serviceCardHighlightLabel: 'Most popular',
  serviceCardsFootnote: null,
  aboutSectionTitle: 'About Section',
  aboutSectionDesc: 'Tell visitors about your business, mission, and team.',
  aboutEyebrowPlaceholder: 'About Us',
  teamSectionTitle: null,
  teamSectionDesc: null,
  teamIntroPlaceholder: null,
  teamMemberSubtitleHint: null,
  teamCardsTitle: null,
  teamCardsHelp: null,
  testimonialsSectionTitle: 'Testimonials',
  testimonialsSectionDesc: 'Customer reviews with star ratings - up to 6.',
  testimonialsEyebrowPlaceholder: 'Testimonials',
  testimonialsTitlePlaceholder: null,
  gallerySectionTitle: 'Gallery',
  gallerySectionDesc: 'Show the space, the work, or the people. 4-12 images.',
  galleryTitlePlaceholder: 'Inside the space',
  faqSectionTitle: 'FAQ',
  faqSectionDesc: 'Pre-empt the phone calls. 4-8 questions, one-click accordion.',
  contactSectionTitle: 'Contact Section',
  contactSectionDesc: 'Contact information and enquiry form.',
  contactEyebrowPlaceholder: 'Contact Us',
  contactBodyFallback: 'Have questions? Reach out and we will get back to you.',
  ctaBodyFallback: 'Send an enquiry and we will get back to you.',
  pricingSectionTitle: 'Pricing',
  pricingSectionDesc: "Plan comparison cards with prices and features. Up to 4 tiers - the highlighted one gets the 'Most popular' badge.",
  pricingEyebrowPlaceholder: 'Pricing',
  pricingTierTitle: 'Pricing tiers',
  pricingTierHelp: 'Each tier: title, price, badge, description, feature list, and a button label. Tick Highlight on the one you want to stand out.',
};

const BUILDER_PROFILES = {
  general: {
    id: 'general',
    name: 'General website',
    match: { fallback: true },
    recommendedLayoutKeys: ['classic', 'bento-modern', 'consultancy', 'corporate-boardroom', 'community-hub', 'magazine', 'minimal-mono', 'logistics-network'],
    sections: DEFAULT_SECTIONS,
    copy: PROFILE_DEFAULTS,
  },
  restaurant: {
    id: 'restaurant',
    name: 'Restaurant website',
    match: {
      keywords: [
        'restaurant', 'dining', 'diner', 'bistro', 'cafe', 'coffee', 'bar', 'pub',
        'food', 'menu', 'takeaway', 'sushi', 'seafood', 'vegan', 'catering',
      ],
    },
    recommendedLayoutKeys: [
      'restaurant-menu', 'chef-tasting-room', 'cafe-counter', 'private-dining', 'catering-events',
      'bar-nightlife', 'bakery-display', 'wine-cellar', 'food-truck', 'luxury-serif',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Menu', desc: 'Signature dishes, dining experiences, and menu highlights', defaultOn: true },
      about: { label: 'Story', desc: 'Restaurant story, room, kitchen, and hospitality promise', defaultOn: true },
      team: { label: 'Hosts', desc: 'Host team, chef, sommelier, or front-of-house profiles', defaultOn: true },
      gallery: { label: 'Dining gallery', desc: 'Food, dining rooms, bar, events, and atmosphere', defaultOn: true },
      testimonials: { label: 'Guest reviews', desc: 'Guest quotes, event feedback, and dining proof', defaultOn: true },
      pricing: { label: 'Dining packages', desc: 'Set menus, minimum spends, events, or tasting packages', defaultOn: true },
      faq: { label: 'FAQ', desc: 'Dress code, deposits, large parties, allergies, and cancellation rules', defaultOn: true },
      contact: { label: 'Visit', desc: 'Address, opening hours, phone, map, and parking notes', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'Restaurant details',
      ctaLabel: 'Reserve a table',
      heroLine3Placeholder: 'Reserve online, share dining notes, and arrive to a prepared table.',
      restaurantReadinessTitle: 'Restaurant launch readiness',
      restaurantReadinessBody: 'Use this website editor for menu, dining rooms, private dining, reviews and visit details. Capacity, service periods, waitlist, deposits, minimum spend and host-stand operations live in Reservations and Tables.',
      restaurantReadinessItems: 'Menu cards tell guests why to book|Tables control real availability|Host Stand handles walk-ins and waitlist|Policies are shown before confirmation',
      trustBadgesHint: 'Three short phrases shown below the CTA, such as live table availability, dietary notes, or private dining.',
      servicesSectionTitle: 'Menu Section',
      servicesSectionDesc: 'Highlight dishes, dining experiences, private dining, and menu-driven reservation options.',
      servicesEyebrowPlaceholder: 'Our Menu',
      servicesTitlePlaceholder: 'Seasonal menu highlights',
      serviceCardsTitle: 'Menu cards',
      serviceCardsHelp: 'Add cards for signature dishes, chef counter, private dining, set menus, or events. Reservation rules live in Tables and Reservations.',
      serviceCardSingular: 'menu card',
      serviceCardNamePlaceholder: 'Dish, menu, or dining experience',
      serviceCardDescriptionPlaceholder: 'Ingredients, service style, or dining notes',
      serviceCardDurationPlaceholder: 'Lunch / dinner / 90 min',
      serviceCardFeaturesPlaceholder: 'Dietary notes, pairing, serving style, highlights',
      serviceCardHighlightLabel: 'Feature',
      serviceCardsFootnote: 'These cards drive the homepage Menu section. Table capacity and bookable reservation rules live in Tables and Reservations.',
      teamSectionTitle: 'Hosts Section',
      teamSectionDesc: 'Show host, chef, sommelier, or front-of-house profiles.',
      teamIntroPlaceholder: 'Our front-of-house team coordinates tables, guest notes, service pacing, and warm arrivals.',
      teamMemberSubtitleHint: "Shown under each profile when their own subtitle is empty, such as Host, Chef, or Sommelier.",
      teamCardsTitle: 'Hosts',
      teamCardsHelp: 'Add a card for each host, chef, sommelier, or front-of-house person you want to feature.',
      testimonialsSectionTitle: 'Guest reviews',
      testimonialsSectionDesc: 'Guest reviews, private dining feedback, and dining proof - up to 6.',
      testimonialsEyebrowPlaceholder: 'Guest reviews',
      testimonialsTitlePlaceholder: 'What Guests Say',
      galleryTitlePlaceholder: 'Inside the dining room',
      contactSectionTitle: 'Visit Section',
      contactSectionDesc: 'Address, phone, opening notes, and reservation call-to-action.',
      contactEyebrowPlaceholder: 'Visit us',
      contactBodyFallback: 'Reserve online, call for large parties, or send private dining details.',
      ctaBodyFallback: 'Reserve your table online and share any dining notes before you arrive.',
      pricingSectionTitle: 'Dining packages',
      pricingSectionDesc: 'Set menus, minimum spends, private dining packages, or tasting experiences.',
      pricingEyebrowPlaceholder: 'Dining packages',
      pricingTierTitle: 'Dining packages',
      pricingTierHelp: 'Each package: title, price or minimum spend, badge, description, inclusions, and a button label. Tick Highlight on the one you want to stand out.',
    },
  },
  healthcare: {
    id: 'healthcare',
    name: 'Healthcare website',
    match: {
      keywords: [
        'healthcare', 'health', 'medical', 'clinic', 'doctor', 'dental', 'dentist',
        'physio', 'therapy', 'therapist', 'psychology', 'dermatology', 'optometry',
        'veterinary', 'ultrasound', 'vaccination',
      ],
    },
    recommendedLayoutKeys: [
      'medical-trust', 'healthcare', 'clinic-timeline', 'dental-clinic', 'therapy-calm',
      'specialist-practice', 'diagnostic-lab', 'veterinary-care', 'maternity-care', 'minimal-mono',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Treatments', desc: 'Treatments, consultations, and care pathways', defaultOn: true },
      team: { label: 'Clinicians', desc: 'Doctors, clinicians, therapists, or care team profiles', defaultOn: true },
      testimonials: { label: 'Patient stories', desc: 'Patient reviews and outcome proof', defaultOn: true },
      pricing: { label: 'Fees', desc: 'Consultation fees, care plans, or package pricing', defaultOn: true },
      contact: { label: 'Visit', desc: 'Clinic address, hours, phone, and booking call-to-action', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'Clinic details',
      servicesTitlePlaceholder: 'Care and treatments',
      serviceCardSingular: 'treatment',
      serviceCardNamePlaceholder: 'Treatment or consultation name',
      serviceCardDescriptionPlaceholder: 'What it helps with and what patients can expect',
      serviceCardDurationPlaceholder: '30 min',
      serviceCardsFootnote: 'These cards drive the homepage Treatments section. Bookable services, prices, and staff routing live in the Services tab.',
      teamIntroPlaceholder: 'Our qualified care team combines experience, clear communication, and practical next steps.',
      testimonialsTitlePlaceholder: 'What Patients Say',
      galleryTitlePlaceholder: 'Inside the clinic',
      contactBodyFallback: 'Have questions? Reach out or book online.',
      ctaBodyFallback: 'Book your appointment online today.',
      pricingSectionTitle: 'Fees',
      pricingEyebrowPlaceholder: 'Fees',
    },
  },
  beauty: {
    id: 'beauty',
    name: 'Beauty and wellness website',
    match: {
      keywords: [
        'beauty', 'wellness', 'salon', 'spa', 'barber', 'hair', 'nail', 'lash',
        'brow', 'makeup', 'massage', 'skin', 'skincare', 'tattoo', 'piercing',
        'reiki', 'meditation',
      ],
    },
    recommendedLayoutKeys: [
      'salon-soft', 'boutique-bento', 'spa-retreat', 'skincare-clinic', 'barber-shop',
      'yoga-studio', 'wellness-coach', 'fitness-program', 'boutique-card', 'wellness-warm',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Services', desc: 'Treatments, packages, looks, and appointment options', defaultOn: true },
      team: { label: 'Artists', desc: 'Stylists, therapists, artists, or specialists', defaultOn: true },
      gallery: { label: 'Lookbook', desc: 'Results, room details, products, and atmosphere', defaultOn: true },
      pricing: { label: 'Packages', desc: 'Service packages, add-ons, memberships, or bundles', defaultOn: true },
      contact: { label: 'Visit', desc: 'Studio address, hours, phone, and booking call-to-action', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'Studio details',
      servicesTitlePlaceholder: 'Services and treatments',
      serviceCardSingular: 'service',
      serviceCardNamePlaceholder: 'Service, treatment, or package',
      serviceCardDescriptionPlaceholder: 'Result, process, prep notes, or ideal client',
      serviceCardDurationPlaceholder: '45 min',
      serviceCardsFootnote: 'These cards drive the homepage Services section. Bookable appointment rules live in the Services tab.',
      teamIntroPlaceholder: 'Our specialists help clients choose the right service, timing, and aftercare.',
      testimonialsTitlePlaceholder: 'What Clients Say',
      galleryTitlePlaceholder: 'Recent work and studio moments',
      pricingSectionTitle: 'Packages',
      pricingEyebrowPlaceholder: 'Packages',
    },
  },
  personal: {
    id: 'personal',
    name: 'Personal brand website',
    match: {
      keywords: [
        'personal brand', 'coach', 'speaker', 'author', 'creator', 'influencer',
        'podcast', 'podcaster', 'blogger', 'youtuber', 'model', 'actor', 'dancer',
      ],
    },
    recommendedLayoutKeys: [
      'personal-brand', 'coach-authority', 'speaker-stage', 'writer-editorial', 'creator-channel',
      'podcast-studio', 'artist-collection', 'photographer-gallery', 'minimal-mono', 'editorial-mono',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Offers', desc: 'Services, sessions, talks, products, or featured work', defaultOn: true },
      about: { label: 'Bio', desc: 'Personal story, positioning, credentials, and point of view', defaultOn: true },
      team: { label: 'Featured people', desc: 'Founder, collaborators, or support team', defaultOn: false },
      gallery: { label: 'Media', desc: 'Press, talks, portfolio images, social proof, or featured appearances', defaultOn: true },
      testimonials: { label: 'Proof', desc: 'Client notes, audience feedback, press quotes, or outcomes', defaultOn: true },
      pricing: { label: 'Packages', desc: 'Talks, sessions, retainers, or offer tiers', defaultOn: true },
      contact: { label: 'Enquire', desc: 'Booking, collaboration, media, or project enquiry form', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'Personal brand details',
      ctaLabel: 'Start a conversation',
      heroLine3Placeholder: 'Share the audience, outcome, or collaboration you are known for.',
      servicesTitlePlaceholder: 'Ways to work together',
      serviceCardSingular: 'offer',
      serviceCardNamePlaceholder: 'Offer, session, talk, or service',
      serviceCardDescriptionPlaceholder: 'Who it is for, the outcome, and what happens next',
      serviceCardDurationPlaceholder: 'Session / keynote / project',
      serviceCardFeaturesPlaceholder: 'Outcomes, deliverables, format, next steps',
      teamSectionTitle: 'Featured people',
      testimonialsSectionTitle: 'Proof',
      testimonialsEyebrowPlaceholder: 'Proof',
      gallerySectionTitle: 'Media',
      galleryTitlePlaceholder: 'Featured work and appearances',
      pricingSectionTitle: 'Packages',
      pricingEyebrowPlaceholder: 'Packages',
      contactSectionTitle: 'Enquiry Section',
      contactEyebrowPlaceholder: 'Enquire',
    },
  },
  retail: {
    id: 'retail',
    name: 'Retail and catalog website',
    match: {
      keywords: [
        'retail', 'store', 'shop', 'catalog', 'catalogue', 'fashion', 'grocery',
        'electronics', 'furniture', 'handmade', 'wholesale', 'subscription box',
        'product brand',
      ],
    },
    recommendedLayoutKeys: [
      'commerce', 'fashion-drop', 'grocery-market', 'electronics-catalog', 'furniture-showroom',
      'beauty-brand-store', 'subscription-box', 'wholesale-catalog', 'handmade-boutique', 'retail-bento',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Collections', desc: 'Product lines, categories, best sellers, or buying paths', defaultOn: true },
      about: { label: 'Brand story', desc: 'Store story, sourcing, values, and buying confidence', defaultOn: true },
      team: { label: 'Makers', desc: 'Founders, makers, buyers, or store team', defaultOn: false },
      gallery: { label: 'Product gallery', desc: 'Products, campaigns, lifestyle images, and store moments', defaultOn: true },
      testimonials: { label: 'Reviews', desc: 'Customer reviews, ratings, and social proof', defaultOn: true },
      pricing: { label: 'Offers', desc: 'Bundles, memberships, wholesale tiers, or featured offers', defaultOn: true },
      faq: { label: 'FAQ', desc: 'Shipping, returns, pickup, payment, wholesale, and product questions', defaultOn: true },
      contact: { label: 'Support', desc: 'Support details, policies, and enquiry form', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'Store details',
      ctaLabel: 'Shop now',
      heroLine3Placeholder: 'Highlight best sellers, delivery, pickup, launches, or current offers.',
      servicesTitlePlaceholder: 'Featured collections',
      serviceCardSingular: 'collection',
      serviceCardNamePlaceholder: 'Collection, category, or offer',
      serviceCardDescriptionPlaceholder: 'What is included, who it suits, and why customers choose it',
      serviceCardDurationPlaceholder: 'Delivery / pickup',
      serviceCardFeaturesPlaceholder: 'Best sellers, materials, availability, delivery notes',
      testimonialsSectionTitle: 'Reviews',
      testimonialsEyebrowPlaceholder: 'Reviews',
      gallerySectionTitle: 'Product gallery',
      galleryTitlePlaceholder: 'Products and store moments',
      pricingSectionTitle: 'Offers',
      pricingEyebrowPlaceholder: 'Offers',
      contactSectionTitle: 'Support Section',
      contactEyebrowPlaceholder: 'Support',
    },
  },
  education: {
    id: 'education',
    name: 'Education website',
    match: {
      keywords: [
        'education', 'training', 'school', 'academy', 'course', 'tuition',
        'tutor', 'math', 'maths', 'mathematics', 'science', 'english',
        'ielts', 'pte', 'coaching', 'workshop', 'seminar', 'learning',
      ],
    },
    recommendedLayoutKeys: [
      'academy', 'school-prospectus', 'tutor-conversion', 'course-launch', 'cohort-academy',
      'preschool-warm', 'language-institute', 'training-enterprise', 'editorial-feature', 'minimal-mono',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Courses', desc: 'Courses, subjects, cohorts, and learning outcomes', defaultOn: true },
      team: { label: 'Tutors', desc: 'Tutors, instructors, or mentors', defaultOn: true },
      testimonials: { label: 'Student results', desc: 'Learner outcomes, parent feedback, or graduate proof', defaultOn: true },
      pricing: { label: 'Fees', desc: 'Course fees, cohorts, subscriptions, or bundles', defaultOn: true },
      contact: { label: 'Enquire', desc: 'Course enquiry, campus details, and contact options', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'School details',
      ctaLabel: 'Enquire now',
      heroLine3Placeholder: 'Share the learning outcome, enrolment path, or next cohort.',
      servicesTitlePlaceholder: 'Courses and programs',
      serviceCardSingular: 'course',
      serviceCardNamePlaceholder: 'Course, subject, or program',
      serviceCardDescriptionPlaceholder: 'Outcome, level, format, and who it is for',
      serviceCardDurationPlaceholder: '6 weeks',
      serviceCardFeaturesPlaceholder: 'Modules, outcomes, format, support',
      serviceCardsFootnote: 'These cards drive the homepage Courses section. Enquiries land in the Enquiries tab.',
      teamIntroPlaceholder: 'Our instructors guide learners with clear structure, feedback, and practical next steps.',
      testimonialsSectionTitle: 'Student results',
      testimonialsEyebrowPlaceholder: 'Student results',
      testimonialsTitlePlaceholder: 'What Learners Say',
      pricingSectionTitle: 'Fees',
      pricingEyebrowPlaceholder: 'Fees',
      contactSectionTitle: 'Enquiry Section',
      contactEyebrowPlaceholder: 'Enquire',
    },
  },
  professional: {
    id: 'professional',
    name: 'Professional services website',
    match: {
      keywords: [
        'legal', 'law', 'lawyer', 'firm', 'finance', 'financial', 'accountant',
        'tax', 'consultant', 'advisor', 'immigration', 'insurance', 'wealth',
      ],
    },
    recommendedLayoutKeys: [
      'consultancy', 'law-prestige', 'accounting-trust', 'finance-advisor', 'immigration-pathway',
      'consultant-diagnostic', 'recruitment-board', 'notary-simple', 'corporate-boardroom', 'editorial-mono',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Practice areas', desc: 'Service lines, advisory areas, and client-fit signals', defaultOn: true },
      team: { label: 'Advisors', desc: 'Partners, advisors, consultants, or case handlers', defaultOn: true },
      testimonials: { label: 'Client proof', desc: 'Client outcomes, reviews, or trust proof', defaultOn: true },
      pricing: { label: 'Engagements', desc: 'Packages, retainers, fixed fees, or consultation options', defaultOn: true },
      contact: { label: 'Consultation', desc: 'Consultation CTA, office details, and enquiry form', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      ctaLabel: 'Request consultation',
      servicesTitlePlaceholder: 'How we can help',
      serviceCardSingular: 'practice area',
      serviceCardNamePlaceholder: 'Practice area or advisory service',
      serviceCardDescriptionPlaceholder: 'Matter type, client fit, and next step',
      serviceCardDurationPlaceholder: 'Consultation',
      serviceCardFeaturesPlaceholder: 'Scope, documents, timeline, eligibility',
      teamIntroPlaceholder: 'Our team brings clear advice, documented process, and practical next steps.',
      testimonialsSectionTitle: 'Client proof',
      testimonialsEyebrowPlaceholder: 'Client proof',
      testimonialsTitlePlaceholder: 'What Clients Say',
      pricingSectionTitle: 'Engagements',
      pricingEyebrowPlaceholder: 'Engagements',
      contactSectionTitle: 'Consultation Section',
      contactEyebrowPlaceholder: 'Consultation',
    },
  },
  industrial: {
    id: 'industrial',
    name: 'Industrial and logistics website',
    match: {
      keywords: [
        'industrial', 'manufacturing', 'factory', 'logistics', 'transport', 'freight',
        'automotive', 'agriculture', 'farm', 'warehouse', 'distribution', 'fleet',
      ],
    },
    recommendedLayoutKeys: [
      'industrial-capability', 'logistics-network', 'trades-quote', 'corporate-boardroom',
      'tech-grid', 'bento-modern', 'agency-feature', 'classic',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Capabilities', desc: 'Capabilities, service lines, capacity, and operational scope', defaultOn: true },
      about: { label: 'Operations', desc: 'Process, facilities, safety, quality, and reliability proof', defaultOn: true },
      team: { label: 'Team', desc: 'Leadership, operators, technicians, or account managers', defaultOn: true },
      gallery: { label: 'Facilities', desc: 'Facilities, equipment, fleet, products, and work examples', defaultOn: true },
      testimonials: { label: 'Client proof', desc: 'Operational proof, case notes, and client feedback', defaultOn: true },
      pricing: { label: 'Quotes', desc: 'Quote paths, retainers, service levels, or capacity packages', defaultOn: true },
      contact: { label: 'Quote', desc: 'Quote request, service area, sales contact, and operating details', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'Operations details',
      ctaLabel: 'Request a quote',
      heroLine3Placeholder: 'Mention capacity, service areas, quality proof, or the best next step.',
      servicesTitlePlaceholder: 'Capabilities and services',
      serviceCardSingular: 'capability',
      serviceCardNamePlaceholder: 'Capability, service line, or solution',
      serviceCardDescriptionPlaceholder: 'Scope, capacity, compliance, process, or operational outcome',
      serviceCardDurationPlaceholder: 'Lead time',
      serviceCardFeaturesPlaceholder: 'Capacity, locations, certifications, equipment, service levels',
      gallerySectionTitle: 'Facilities',
      galleryTitlePlaceholder: 'Operations and capability',
      pricingSectionTitle: 'Quote options',
      pricingEyebrowPlaceholder: 'Quotes',
      contactSectionTitle: 'Quote Section',
      contactEyebrowPlaceholder: 'Request a quote',
    },
  },
  property: {
    id: 'property',
    name: 'Property and construction website',
    match: {
      keywords: [
        'real estate', 'property', 'construction', 'builder', 'architect',
        'renovation', 'contractor', 'interior', 'landscaping', 'plumbing',
        'roofing', 'cleaning', 'home services',
      ],
    },
    recommendedLayoutKeys: [
      'real-estate-showcase', 'architect-portfolio', 'builder-projects', 'interior-lookbook',
      'landscaping-before-after', 'trades-quote', 'cleaning-service', 'home-maintenance', 'bento-modern', 'agency-feature',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Services', desc: 'Service lines, project types, and quote-ready offers', defaultOn: true },
      gallery: { label: 'Projects', desc: 'Completed work, before-after moments, and site details', defaultOn: true },
      testimonials: { label: 'Client proof', desc: 'Project feedback, outcomes, and trust proof', defaultOn: true },
      pricing: { label: 'Quotes', desc: 'Packages, estimate ranges, retainers, or project types', defaultOn: true },
      contact: { label: 'Quote', desc: 'Quote request, service area, and contact details', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      ctaLabel: 'Request a quote',
      heroLine3Placeholder: 'Mention service areas, project types, or the best next step.',
      servicesTitlePlaceholder: 'Services and project types',
      serviceCardSingular: 'service',
      serviceCardNamePlaceholder: 'Service or project type',
      serviceCardDescriptionPlaceholder: 'Scope, property type, process, or outcome',
      serviceCardDurationPlaceholder: 'Timeline',
      serviceCardFeaturesPlaceholder: 'Scope, materials, service area, warranty',
      galleryTitlePlaceholder: 'Recent projects',
      pricingSectionTitle: 'Quote options',
      pricingEyebrowPlaceholder: 'Quotes',
      contactSectionTitle: 'Quote Section',
      contactEyebrowPlaceholder: 'Request a quote',
    },
  },
  creative: {
    id: 'creative',
    name: 'Portfolio website',
    match: {
      keywords: [
        'portfolio', 'creative', 'designer', 'developer', 'writer', 'photographer',
        'artist', 'studio', 'agency', 'marketing', 'brand', 'content', 'creator',
        'videographer',
      ],
    },
    recommendedLayoutKeys: [
      'studio-portfolio', 'photographer-gallery', 'writer-editorial', 'developer-systems', 'designer-case-study',
      'creator-channel', 'podcast-studio', 'speaker-stage', 'coach-authority', 'artist-collection', 'agency-casebook', 'creative-mosaic',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Work', desc: 'Selected services, case studies, offers, or capabilities', defaultOn: true },
      team: { label: 'People', desc: 'Founder, collaborators, or studio team', defaultOn: true },
      gallery: { label: 'Portfolio', desc: 'Selected projects, visuals, and proof', defaultOn: true },
      testimonials: { label: 'Client notes', desc: 'Client quotes and project proof', defaultOn: true },
      pricing: { label: 'Offers', desc: 'Packages, retainers, or project starting points', defaultOn: true },
      contact: { label: 'Brief', desc: 'Project brief, contact details, and enquiry form', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      ctaLabel: 'Start a brief',
      heroLine3Placeholder: 'Mention the kind of work, audience, or ideal collaboration.',
      servicesTitlePlaceholder: 'Selected work and services',
      serviceCardSingular: 'offer',
      serviceCardNamePlaceholder: 'Service, project type, or case study',
      serviceCardDescriptionPlaceholder: 'Outcome, scope, audience, or process',
      serviceCardDurationPlaceholder: 'Timeline',
      serviceCardFeaturesPlaceholder: 'Deliverables, process, tools, outcomes',
      gallerySectionTitle: 'Portfolio',
      galleryTitlePlaceholder: 'Selected work',
      testimonialsSectionTitle: 'Client notes',
      testimonialsEyebrowPlaceholder: 'Client notes',
      pricingSectionTitle: 'Offers',
      pricingEyebrowPlaceholder: 'Offers',
      contactSectionTitle: 'Brief Section',
      contactEyebrowPlaceholder: 'Start a brief',
    },
  },
  events: {
    id: 'events',
    name: 'Events and venue website',
    match: {
      keywords: [
        'event', 'events', 'wedding', 'venue', 'planner', 'party', 'conference',
        'festival', 'entertainment', 'performer', 'dj',
      ],
    },
    recommendedLayoutKeys: [
      'event-planner', 'wedding-venue', 'speaker-stage', 'bar-nightlife', 'catering-events',
      'private-dining', 'hotel-resort', 'studio-feature', 'agency-feature', 'luxury-serif',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Events', desc: 'Event types, packages, venues, entertainment, or planning services', defaultOn: true },
      about: { label: 'Experience', desc: 'Venue story, planning approach, atmosphere, and delivery proof', defaultOn: true },
      team: { label: 'Hosts', desc: 'Coordinators, performers, planners, or venue team', defaultOn: true },
      gallery: { label: 'Event gallery', desc: 'Rooms, moments, stages, setups, and guest experience', defaultOn: true },
      testimonials: { label: 'Guest proof', desc: 'Guest, organiser, couple, or client feedback', defaultOn: true },
      pricing: { label: 'Packages', desc: 'Event packages, minimum spends, retainers, or booking tiers', defaultOn: true },
      contact: { label: 'Brief', desc: 'Event enquiry, date, venue, budget, guest count, and contact details', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'Event details',
      ctaLabel: 'Start a brief',
      heroLine3Placeholder: 'Share the event type, date, venue, guest count, or planning outcome.',
      servicesTitlePlaceholder: 'Events and packages',
      serviceCardSingular: 'event offer',
      serviceCardNamePlaceholder: 'Event type, package, or service',
      serviceCardDescriptionPlaceholder: 'Capacity, inclusions, mood, planning support, or delivery notes',
      serviceCardDurationPlaceholder: 'Event length',
      serviceCardFeaturesPlaceholder: 'Capacity, inclusions, setup, timing, venue notes',
      testimonialsSectionTitle: 'Guest proof',
      testimonialsEyebrowPlaceholder: 'Guest proof',
      gallerySectionTitle: 'Event gallery',
      galleryTitlePlaceholder: 'Events and spaces',
      pricingSectionTitle: 'Packages',
      pricingEyebrowPlaceholder: 'Packages',
      contactSectionTitle: 'Brief Section',
      contactEyebrowPlaceholder: 'Start a brief',
    },
  },
  nonprofit: {
    id: 'nonprofit',
    name: 'Community and nonprofit website',
    match: {
      keywords: [
        'nonprofit', 'charity', 'community', 'church', 'ministry', 'religious',
        'foundation', 'association', 'club', 'volunteer', 'campaign',
      ],
    },
    recommendedLayoutKeys: [
      'nonprofit-cause', 'community-hub', 'church-ministry', 'school-prospectus',
      'personal-brand', 'classic', 'bento-modern', 'minimal-mono',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Programs', desc: 'Programs, services, campaigns, ministries, or ways to participate', defaultOn: true },
      about: { label: 'Mission', desc: 'Mission, story, impact, values, and community proof', defaultOn: true },
      team: { label: 'People', desc: 'Leaders, volunteers, board, staff, or community members', defaultOn: true },
      gallery: { label: 'Community', desc: 'Events, programs, people, impact moments, and spaces', defaultOn: true },
      testimonials: { label: 'Stories', desc: 'Impact stories, member notes, community proof, or outcomes', defaultOn: true },
      pricing: { label: 'Ways to help', desc: 'Donation paths, memberships, volunteering, sponsorship, or support tiers', defaultOn: true },
      contact: { label: 'Connect', desc: 'Visit details, enquiry, volunteering, participation, and contact form', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'Organisation details',
      ctaLabel: 'Get involved',
      heroLine3Placeholder: 'Share the mission, who you help, and the next action people can take.',
      servicesTitlePlaceholder: 'Programs and ways to participate',
      serviceCardSingular: 'program',
      serviceCardNamePlaceholder: 'Program, campaign, or way to help',
      serviceCardDescriptionPlaceholder: 'Who it supports, what happens, and how people can join',
      serviceCardDurationPlaceholder: 'Ongoing / event',
      serviceCardFeaturesPlaceholder: 'Impact, eligibility, location, timing, next steps',
      testimonialsSectionTitle: 'Stories',
      testimonialsEyebrowPlaceholder: 'Stories',
      gallerySectionTitle: 'Community',
      galleryTitlePlaceholder: 'Community and impact',
      pricingSectionTitle: 'Ways to help',
      pricingEyebrowPlaceholder: 'Ways to help',
      contactSectionTitle: 'Connect Section',
      contactEyebrowPlaceholder: 'Connect',
    },
  },
  hospitality: {
    id: 'hospitality',
    name: 'Hospitality website',
    match: {
      keywords: ['hotel', 'travel', 'tourism', 'venue', 'wedding venue', 'yacht', 'charter', 'accommodation'],
    },
    recommendedLayoutKeys: [
      'hotel-resort', 'travel-experiences', 'wedding-venue', 'event-planner',
      'luxury-serif', 'editorial-feature', 'boutique-card', 'magazine', 'private-dining',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      services: { label: 'Experiences', desc: 'Rooms, experiences, packages, and venue options', defaultOn: true },
      gallery: { label: 'Gallery', desc: 'Rooms, spaces, views, events, and atmosphere', defaultOn: true },
      pricing: { label: 'Packages', desc: 'Packages, minimum spends, or stay options', defaultOn: true },
      contact: { label: 'Enquire', desc: 'Booking enquiry, location, and contact details', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      ctaLabel: 'Enquire now',
      servicesTitlePlaceholder: 'Experiences and packages',
      serviceCardSingular: 'experience',
      serviceCardNamePlaceholder: 'Room, package, or experience',
      serviceCardDescriptionPlaceholder: 'Capacity, mood, inclusions, or booking notes',
      serviceCardDurationPlaceholder: 'Stay / event length',
      galleryTitlePlaceholder: 'Inside the space',
      pricingSectionTitle: 'Packages',
      pricingEyebrowPlaceholder: 'Packages',
      contactSectionTitle: 'Enquiry Section',
      contactEyebrowPlaceholder: 'Enquire',
    },
  },
  ecommerce: {
    id: 'ecommerce',
    name: 'Storefront website',
    match: { verticals: ['ECOMMERCE'] },
    recommendedLayoutKeys: [
      'commerce', 'fashion-drop', 'grocery-market', 'electronics-catalog', 'furniture-showroom',
      'beauty-brand-store', 'subscription-box', 'wholesale-catalog', 'handmade-boutique', 'retail-bento',
    ],
    sections: {
      ...DEFAULT_SECTIONS,
      about: { label: 'About', desc: 'Store story and buying confidence', defaultOn: true },
      gallery: { label: 'Brand gallery', desc: 'Product, campaign, and lifestyle images', defaultOn: true },
      testimonials: { label: 'Reviews', desc: 'Customer reviews and social proof', defaultOn: true },
      faq: { label: 'FAQ', desc: 'Shipping, returns, pickup, payment, and product questions', defaultOn: true },
      contact: { label: 'Support', desc: 'Support details, store policies, and enquiry form', defaultOn: true },
    },
    copy: {
      ...PROFILE_DEFAULTS,
      businessLabel: 'Store details',
      ctaLabel: 'Shop now',
      heroLine3Placeholder: 'Highlight delivery, pickup, best sellers, or current offers.',
      testimonialsSectionTitle: 'Reviews',
      testimonialsEyebrowPlaceholder: 'Reviews',
      testimonialsTitlePlaceholder: 'What Customers Say',
      gallerySectionTitle: 'Brand gallery',
      galleryTitlePlaceholder: 'Products and store moments',
      contactSectionTitle: 'Support Section',
      contactSectionDesc: 'Support information and enquiry form.',
      contactEyebrowPlaceholder: 'Support',
      contactBodyFallback: 'Need help? Send a message and our team will get back to you.',
      ctaBodyFallback: 'Browse products, offers, and store updates.',
    },
  },
};

function normalize(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function collectSignals({ themeKey, theme, business, vertical }) {
  const values = [
    vertical,
    themeKey,
    theme?.key,
    theme?.name,
    theme?.category,
    theme?.industry,
    business?.name,
    business?.slug,
    business?.category,
    business?.profession,
    business?.description,
    business?.vertical,
    ...(Array.isArray(theme?.tags) ? theme.tags : []),
  ];
  return normalize(values.filter(Boolean).join(' '));
}

function hasKeyword(signals, keyword) {
  const normalized = normalize(keyword);
  if (!normalized) return false;
  if (!normalized.includes(' ')) {
    return new RegExp(`(^| )${normalized}( |$)`).test(signals);
  }
  return signals === normalized || signals.includes(normalized);
}

function mergeProfile(profile) {
  return {
    ...profile,
    sections: { ...DEFAULT_SECTIONS, ...(profile.sections || {}) },
    copy: { ...PROFILE_DEFAULTS, ...(profile.copy || {}) },
  };
}

export function resolveBuilderProfile({ themeKey, theme, business, vertical } = {}) {
  const normalizedVertical = String(vertical || business?.vertical || '').toUpperCase();

  for (const profile of Object.values(BUILDER_PROFILES)) {
    if (profile.match?.verticals?.includes(normalizedVertical)) return mergeProfile(profile);
  }

  const signals = collectSignals({ themeKey, theme, business, vertical });
  for (const profile of Object.values(BUILDER_PROFILES)) {
    if (profile.match?.fallback) continue;
    if ((profile.match?.keywords || []).some((keyword) => hasKeyword(signals, keyword))) {
      return mergeProfile(profile);
    }
  }

  return mergeProfile(BUILDER_PROFILES.general);
}

export const BUILDER_PROFILE_IDS = Object.keys(BUILDER_PROFILES);

export default BUILDER_PROFILES;
