ALTER TABLE "QaIssue" ALTER COLUMN "status" SET DEFAULT 'DEVELOPMENT';

UPDATE "QaIssue"
SET "status" = CASE "status"
  WHEN 'NEW' THEN 'DEVELOPMENT'
  WHEN 'IN_DEVELOPMENT' THEN 'DEVELOPMENT'
  WHEN 'FIXED_BY_AI' THEN 'READY_FOR_QA'
  WHEN 'VERIFIED' THEN 'COMPLETED'
  WHEN 'CLOSED' THEN 'COMPLETED'
  WHEN 'PENDING_PM_APPROVAL' THEN 'DEVELOPMENT'
  WHEN 'APPROVED' THEN 'DEVELOPMENT'
  WHEN 'PLANNED' THEN 'DEVELOPMENT'
  WHEN 'REJECTED' THEN 'COMPLETED'
  ELSE "status"
END
WHERE "status" IN (
  'NEW',
  'IN_DEVELOPMENT',
  'FIXED_BY_AI',
  'VERIFIED',
  'CLOSED',
  'PENDING_PM_APPROVAL',
  'APPROVED',
  'PLANNED',
  'REJECTED'
);

UPDATE "QaIssueComment"
SET "fromStatus" = CASE "fromStatus"
  WHEN 'NEW' THEN 'DEVELOPMENT'
  WHEN 'IN_DEVELOPMENT' THEN 'DEVELOPMENT'
  WHEN 'FIXED_BY_AI' THEN 'READY_FOR_QA'
  WHEN 'VERIFIED' THEN 'COMPLETED'
  WHEN 'CLOSED' THEN 'COMPLETED'
  WHEN 'PENDING_PM_APPROVAL' THEN 'DEVELOPMENT'
  WHEN 'APPROVED' THEN 'DEVELOPMENT'
  WHEN 'PLANNED' THEN 'DEVELOPMENT'
  WHEN 'REJECTED' THEN 'COMPLETED'
  ELSE "fromStatus"
END
WHERE "fromStatus" IN (
  'NEW',
  'IN_DEVELOPMENT',
  'FIXED_BY_AI',
  'VERIFIED',
  'CLOSED',
  'PENDING_PM_APPROVAL',
  'APPROVED',
  'PLANNED',
  'REJECTED'
);

UPDATE "QaIssueComment"
SET "toStatus" = CASE "toStatus"
  WHEN 'NEW' THEN 'DEVELOPMENT'
  WHEN 'IN_DEVELOPMENT' THEN 'DEVELOPMENT'
  WHEN 'FIXED_BY_AI' THEN 'READY_FOR_QA'
  WHEN 'VERIFIED' THEN 'COMPLETED'
  WHEN 'CLOSED' THEN 'COMPLETED'
  WHEN 'PENDING_PM_APPROVAL' THEN 'DEVELOPMENT'
  WHEN 'APPROVED' THEN 'DEVELOPMENT'
  WHEN 'PLANNED' THEN 'DEVELOPMENT'
  WHEN 'REJECTED' THEN 'COMPLETED'
  ELSE "toStatus"
END
WHERE "toStatus" IN (
  'NEW',
  'IN_DEVELOPMENT',
  'FIXED_BY_AI',
  'VERIFIED',
  'CLOSED',
  'PENDING_PM_APPROVAL',
  'APPROVED',
  'PLANNED',
  'REJECTED'
);
