'use strict';

/*
 * imports.live.test.js — LIVE (hr_test) proof of Feature 18 Data Migration / Bulk
 * Import + back-dated auto-generation. Plain-node (built-in assert, NO jest).
 *
 * Run (DATABASE_URL must target the hr_test schema):
 *   DATABASE_URL="$HR_URL" node src/hr/migration/__tests__/imports.live.test.js
 * where $HR_URL = the repo .env DATABASE_URL + '?schema=hr_test'. Apply the
 * Feature 18 migration to hr_test FIRST. Uses the seed 'demo' tenant's IN-HQ
 * entity + IN-STAFF-CTC structure. Every row written is torn down at the end.
 *
 * Proves (per the spec Verify section):
 *   A. EMPLOYEE import: dry-run preview + idempotent commit (re-commit = no dupes).
 *   B. COMPENSATION import → CTC via deriveBreakup (CompensationRevision + lines).
 *   C. ATTENDANCE (DAILY) back-dated import (idempotent, locked-day not clobbered).
 *   D. PAYROLL_HISTORY autogen: a MIGRATED run computes a payslip THROUGH the
 *      engine, and it MATCHES a manually-run payslip for the same inputs.
 *   E. Dry-run for PAYROLL_HISTORY shows engine-true net pay + persists nothing.
 *   F. REIMBURSEMENT import generates a claim with claimed + approved amounts.
 *   G. Bad rows are REPORTED (ERROR), never silently dropped; the annotated report
 *      carries the reason.
 */

const assert = require('assert');
const prisma = require('../../../core/lib/prisma');
const service = require('../imports.service');
const autogen = require('../autogen.service');
const payrollService = require('../../payroll/service');
const csv = require('../parsers/csv');

let failures = 0;
const log = (...a) => console.log(...a);
function ok(cond, msg) { if (cond) log(`  PASS  ${msg}`); else { failures += 1; log(`  FAIL  ${msg}`); } }

const ACTOR = 'f18-import-actor';
const EMP_CODE = 'EMP-F18-001';
const PERIOD = '2025-12';

function b64(text) { return Buffer.from(text, 'utf8').toString('base64'); }

async function cleanup(businessId) {
  // ImportJobs (cascades ImportRows).
  const jobs = await prisma.importJob.findMany({ where: { businessId, OR: [{ fileName: { startsWith: 'f18-' } }, { kind: { in: ['EMPLOYEE', 'COMPENSATION', 'ATTENDANCE', 'PAYROLL_HISTORY', 'REIMBURSEMENT'] }, uploadedBy: ACTOR }] }, select: { id: true } });
  const jobIds = jobs.map((j) => j.id);
  // MIGRATED runs generated by those jobs.
  const runs = await prisma.payRun.findMany({ where: { businessId, importJobId: { in: jobIds.length ? jobIds : ['_none_'] } }, select: { id: true } });
  const runIds = runs.map((r) => r.id);
  if (runIds.length) {
    await prisma.payslip.deleteMany({ where: { payRunId: { in: runIds } } });
    await prisma.payRunLineComponent.deleteMany({ where: { payRunLine: { payRunId: { in: runIds } } } });
    await prisma.payRunLine.deleteMany({ where: { payRunId: { in: runIds } } });
    await prisma.attendancePayInput.deleteMany({ where: { payRunId: { in: runIds } } });
    await prisma.payRun.deleteMany({ where: { id: { in: runIds } } });
  }
  // The manual control run.
  const ctrl = await prisma.payRun.findMany({ where: { businessId, code: { startsWith: 'F18CTRL' } }, select: { id: true } });
  const ctrlIds = ctrl.map((r) => r.id);
  if (ctrlIds.length) {
    await prisma.payslip.deleteMany({ where: { payRunId: { in: ctrlIds } } });
    await prisma.payRunLineComponent.deleteMany({ where: { payRunLine: { payRunId: { in: ctrlIds } } } });
    await prisma.payRunLine.deleteMany({ where: { payRunId: { in: ctrlIds } } });
    await prisma.attendancePayInput.deleteMany({ where: { payRunId: { in: ctrlIds } } });
    await prisma.payRun.deleteMany({ where: { id: { in: ctrlIds } } });
  }
  // The imported employee + everything hung off it.
  const emp = await prisma.employee.findFirst({ where: { businessId, code: EMP_CODE } });
  if (emp) {
    await prisma.attendance.deleteMany({ where: { businessId, employeeId: emp.id } });
    await prisma.expenseClaimLine.deleteMany({ where: { claim: { employeeId: emp.id } } });
    await prisma.expenseClaim.deleteMany({ where: { businessId, employeeId: emp.id } });
    await prisma.salaryComponentLine.deleteMany({ where: { compensation: { employeeId: emp.id } } });
    await prisma.compensationRevision.deleteMany({ where: { businessId, employeeId: emp.id } });
    await prisma.employmentRecord.deleteMany({ where: { businessId, employeeId: emp.id } });
    await prisma.statutoryProfile.deleteMany({ where: { employeeId: emp.id } });
    if (emp.userId) { await prisma.employee.update({ where: { id: emp.id }, data: { userId: null, currentEmploymentRecordId: null } }); }
    else { await prisma.employee.update({ where: { id: emp.id }, data: { currentEmploymentRecordId: null } }); }
    await prisma.employee.deleteMany({ where: { id: emp.id } });
  }
  if (jobIds.length) await prisma.importJob.deleteMany({ where: { id: { in: jobIds } } });
}

async function main() {
  log('\n=== Feature 18 import + autogen proof (LIVE hr_test) ===\n');
  const demo = await prisma.business.findFirst({ where: { slug: 'demo' } });
  if (!demo) throw new Error("Seed tenant 'demo' not found in hr_test");
  const businessId = demo.id;
  const inEntity = await prisma.entity.findFirst({ where: { businessId, code: 'IN-HQ' } });
  const inCal = await prisma.payCalendar.findFirst({ where: { businessId, entityId: inEntity.id } });
  assert(inEntity && inCal, 'IN-HQ entity + calendar present');

  await cleanup(businessId);

  // ── A. EMPLOYEE import — dry-run + commit + idempotent re-commit ──────────────
  const empCsv = [
    'code,firstName,lastName,workEmail,gender,dateOfBirth,dateOfJoining,entityCode,pan',
    `${EMP_CODE},Asha,Rao,asha.f18@acme.in,FEMALE,1993-02-11,2025-04-01,IN-HQ,ABCDE1234X`,
    // a deliberately BAD row (invalid PAN) — must be REPORTED, not dropped.
    'EMP-F18-BAD,Bad,Row,bad.f18@acme.in,MALE,1990-01-01,2025-04-01,IN-HQ,NOTAPAN',
  ].join('\r\n');
  const empJob = await service.createJob({ businessId, actorId: ACTOR, kind: 'EMPLOYEE', entityId: inEntity.id, fileName: 'f18-employee.csv', contentBase64: b64(empCsv) });
  ok(empJob.rowCount === 2, `A1 EMPLOYEE upload parsed 2 rows (got ${empJob.rowCount})`);

  const empDry = await service.dryRun({ businessId, actorId: ACTOR, jobId: empJob.id });
  ok(empDry.errorCount === 1 && empDry.passCount === 1, `A2 dry-run flags 1 ERROR (bad PAN) + 1 PASS (got err=${empDry.errorCount} pass=${empDry.passCount})`);

  const empCommit = await service.commit({ businessId, actorId: ACTOR, jobId: empJob.id });
  ok(empCommit.commitSummary.committed === 1, `A3 commit created 1 employee (got ${empCommit.commitSummary.committed})`);
  const createdEmp = await prisma.employee.findFirst({ where: { businessId, code: EMP_CODE } });
  ok(!!createdEmp, 'A4 employee row exists after commit');
  const badRow = (await prisma.importRow.findMany({ where: { importJobId: empJob.id } })).find((r) => r.rowNumber === 2);
  ok(badRow.status === 'ERROR' && (badRow.findingsJson || []).some((f) => f.code === 'BAD_PAN'), 'A5 bad PAN row REPORTED as ERROR (not dropped)');

  // Idempotent re-commit: re-upload identical bytes → same job, no dupes.
  const empJob2 = await service.createJob({ businessId, actorId: ACTOR, kind: 'EMPLOYEE', entityId: inEntity.id, fileName: 'f18-employee.csv', contentBase64: b64(empCsv) });
  ok(empJob2.id === empJob.id, 'A6 re-upload of identical bytes returns the SAME job (exactly-once on fileHash)');
  const empCount = await prisma.employee.count({ where: { businessId, code: EMP_CODE } });
  ok(empCount === 1, `A7 re-commit did not duplicate the employee (count=${empCount})`);

  // ── B. COMPENSATION import — CTC via deriveBreakup ───────────────────────────
  const compCsv = [
    'employeeCode,effectiveFrom,ctcAnnual,structureCode',
    `${EMP_CODE},2025-04-01,1200000,IN-STAFF-CTC`,
  ].join('\r\n');
  const compJob = await service.createJob({ businessId, actorId: ACTOR, kind: 'COMPENSATION', entityId: inEntity.id, fileName: 'f18-comp.csv', contentBase64: b64(compCsv) });
  const compDry = await service.dryRun({ businessId, actorId: ACTOR, jobId: compJob.id });
  ok(compDry.passCount === 1, `B1 COMPENSATION dry-run PASS (got ${compDry.passCount})`);
  await service.commit({ businessId, actorId: ACTOR, jobId: compJob.id });
  const rev = await prisma.compensationRevision.findFirst({ where: { businessId, employeeId: createdEmp.id }, include: { lines: true } });
  ok(!!rev && rev.lines.length > 0, `B2 CompensationRevision + lines created via deriveBreakup (lines=${rev ? rev.lines.length : 0})`);
  ok(String(rev.ctcAnnual) === '1200000', `B3 revision CTC = 1200000 (got ${rev && rev.ctcAnnual})`);
  // idempotent re-commit of comp
  await service.commit({ businessId, actorId: ACTOR, jobId: compJob.id });
  const revCount = await prisma.compensationRevision.count({ where: { businessId, employeeId: createdEmp.id, effectiveFrom: new Date('2025-04-01T00:00:00Z') } });
  ok(revCount === 1, `B4 re-commit did not duplicate the revision (count=${revCount})`);

  // ── C. ATTENDANCE (DAILY) back-dated import ──────────────────────────────────
  // December 2025 = 31 days. Make all PRESENT except 2 ABSENT (LOP=2 days).
  const attLines = ['employeeCode,date,status'];
  for (let d = 1; d <= 31; d += 1) {
    const day = String(d).padStart(2, '0');
    const status = (d === 10 || d === 20) ? 'ABSENT' : 'PRESENT';
    attLines.push(`${EMP_CODE},2025-12-${day},${status}`);
  }
  const attJob = await service.createJob({ businessId, actorId: ACTOR, kind: 'ATTENDANCE', entityId: inEntity.id, fileName: 'f18-att.csv', contentBase64: b64(attLines.join('\r\n')), options: { attendanceMode: 'DAILY' } });
  const attDry = await service.dryRun({ businessId, actorId: ACTOR, jobId: attJob.id });
  ok(attDry.passCount === 31, `C1 ATTENDANCE dry-run 31 PASS rows (got ${attDry.passCount})`);
  await service.commit({ businessId, actorId: ACTOR, jobId: attJob.id });
  const attRows = await prisma.attendance.count({ where: { businessId, employeeId: createdEmp.id } });
  ok(attRows === 31, `C2 31 daily Attendance rows committed (got ${attRows})`);
  // idempotent re-commit
  await service.commit({ businessId, actorId: ACTOR, jobId: attJob.id });
  const attRows2 = await prisma.attendance.count({ where: { businessId, employeeId: createdEmp.id } });
  ok(attRows2 === 31, `C3 re-commit did not duplicate attendance (count=${attRows2})`);

  // ── D + E. PAYROLL_HISTORY autogen vs a manual run ───────────────────────────
  const payCsv = ['employeeCode,periodMonth', `${EMP_CODE},${PERIOD}`].join('\r\n');
  const payJob = await service.createJob({ businessId, actorId: ACTOR, kind: 'PAYROLL_HISTORY', entityId: inEntity.id, fileName: 'f18-pay.csv', contentBase64: b64(payCsv), options: { payrollMode: 'GENERATE' } });

  // E. Dry-run shows engine-true net pay + persists NOTHING.
  const payDry = await service.dryRun({ businessId, actorId: ACTOR, jobId: payJob.id });
  const dryNet = payDry.preview && payDry.preview.perRow[0] ? payDry.preview.perRow[0].netPay : null;
  ok(dryNet != null && dryNet > 0, `E1 PAYROLL dry-run shows engine-true net pay (₹${dryNet})`);
  const migRunsAfterDry = await prisma.payRun.count({ where: { businessId, importJobId: payJob.id } });
  ok(migRunsAfterDry === 0, `E2 dry-run persisted NO MIGRATED run (count=${migRunsAfterDry})`);

  // D. Commit + autogen → a real MIGRATED run + payslip.
  const payCommit = await service.commit({ businessId, actorId: ACTOR, jobId: payJob.id });
  ok(payCommit.autogen && payCommit.autogen.periods.length === 1, `D1 autogen generated 1 period (got ${payCommit.autogen ? payCommit.autogen.periods.length : 0})`);
  const migRun = await prisma.payRun.findFirst({ where: { businessId, importJobId: payJob.id }, include: { lines: true, payslips: true } });
  ok(!!migRun && migRun.type === 'MIGRATED', `D2 MIGRATED run created (type=${migRun && migRun.type})`);
  ok(migRun.code.endsWith('-MIG'), `D3 MIGRATED run uses the -MIG code suffix (code=${migRun && migRun.code})`);
  ok(migRun.status === 'COMPUTED' && migRun.payslips.length >= 1, `D4 run COMPUTED with payslips through the engine (status=${migRun.status}, payslips=${migRun.payslips.length})`);
  // Isolate OUR imported employee's line (the run computes the whole entity headcount).
  const migLine = migRun.lines.find((l) => l.employeeId === createdEmp.id);
  ok(!!migLine, 'D4a migrated run produced a line for the imported employee');
  const autoNet = migLine ? Number(migLine.netPay) : 0;
  ok(autoNet > 0, `D5 generated payslip has a real net pay (₹${autoNet})`);
  ok(dryNet != null && Math.abs(autoNet - dryNet) < 1, `D6 committed net (₹${autoNet}) matches the dry-run preview (₹${dryNet})`);

  // D7 — the autogen payslip MATCHES a MANUAL run with the SAME inputs. Build a
  // control run for the same period via the live createRun→computeRun path, with
  // the same daily attendance frozen.
  const ctrlRun = await prisma.payRun.create({
    data: {
      businessId, entityId: inEntity.id, payCalendarId: inCal.id, code: `F18CTRL-${PERIOD}`,
      periodStart: new Date('2025-12-01'), periodEnd: new Date('2025-12-31'), payDate: new Date('2025-12-31'),
      sequenceInYear: 9, taxYear: '2025-26', currencyCode: inEntity.payCurrency, status: 'DRAFT',
    },
  });
  // The control run computes the WHOLE entity headcount; isolate OUR employee's line.
  const ctrlDetail = await payrollService.computeRun({ businessId, actorId: ACTOR, payRunId: ctrlRun.id, freezeAttendance: true });
  const ctrlLine = (ctrlDetail.lines || []).find((l) => l.employeeId === createdEmp.id);
  ok(!!ctrlLine, 'D7a manual control run produced a line for the imported employee');
  if (ctrlLine && migLine) {
    const ctrlNet = Number(ctrlLine.netPay);
    ok(Math.abs(ctrlNet - autoNet) < 1, `D7 autogen payslip net (₹${autoNet}) == manual run net (₹${ctrlNet}) — engine-true, no bypass`);
    ok(Math.abs(Number(ctrlLine.grossEarnings) - Number(migLine.grossEarnings)) < 1, 'D8 gross matches the manual run too');
    ok((Number(migLine.lopDays) === 2), `D9 LOP days from imported attendance reached the engine (lop=${migLine.lopDays})`);
  }

  // D10 — autogen is idempotent: re-running produces no second run / no dupes.
  const again = await autogen.runPayrollAutogen({ businessId, actorId: ACTOR, jobId: payJob.id });
  const migRunCount = await prisma.payRun.count({ where: { businessId, importJobId: payJob.id } });
  ok(migRunCount === 1, `D10 re-running autogen did not create a second MIGRATED run (count=${migRunCount})`);

  // ── F. REIMBURSEMENT import → claim with claimed + approved amounts ───────────
  const reimbCsv = [
    'employeeCode,expenseDate,claimedAmount,approvedAmount,status,description',
    `${EMP_CODE},2025-11-15,5000,4500,APPROVED,Client dinner`,
    `${EMP_CODE},2025-11-20,3000,3000,REIMBURSED,Taxi`,
  ].join('\r\n');
  const reimbJob = await service.createJob({ businessId, actorId: ACTOR, kind: 'REIMBURSEMENT', entityId: inEntity.id, fileName: 'f18-reimb.csv', contentBase64: b64(reimbCsv) });
  const reimbDry = await service.dryRun({ businessId, actorId: ACTOR, jobId: reimbJob.id });
  ok(reimbDry.passCount + reimbDry.warnCount === 2, `F1 REIMBURSEMENT dry-run 2 rows ok (pass=${reimbDry.passCount} warn=${reimbDry.warnCount})`);
  await service.commit({ businessId, actorId: ACTOR, jobId: reimbJob.id });
  const claims = await prisma.expenseClaim.findMany({ where: { businessId, employeeId: createdEmp.id }, include: { lines: true }, orderBy: { expenseDate: 'asc' } });
  ok(claims.length === 2, `F2 2 claims generated (got ${claims.length})`);
  const c1 = claims[0];
  ok(String(c1.amount) === '5000' && c1.status === 'APPROVED', `F3 claim #1 claimed=5000 status=APPROVED (got ${c1.amount}/${c1.status})`);
  ok(String(c1.lines[0].amount) === '4500', `F4 claim #1 approved amount on line = 4500 (got ${c1.lines[0].amount})`);
  ok(claims[1].status === 'REIMBURSED' && !!claims[1].importJobId, 'F5 claim #2 REIMBURSED + carries importJobId provenance');
  // idempotent re-commit
  await service.commit({ businessId, actorId: ACTOR, jobId: reimbJob.id });
  const claimCount = await prisma.expenseClaim.count({ where: { businessId, employeeId: createdEmp.id } });
  ok(claimCount === 2, `F6 re-commit did not duplicate claims (count=${claimCount})`);

  // ── G. Annotated report carries status + reason ──────────────────────────────
  const report = await service.buildReportCsv({ businessId, jobId: empJob.id });
  const reportParsed = csv.parseCsv(report.csv);
  const badReportRow = reportParsed.rows.find((r) => r.__status === 'ERROR');
  ok(badReportRow && /BAD_PAN/.test(badReportRow.__reason), 'G1 annotated report carries the ERROR reason for the bad row');

  // ── teardown ──
  await cleanup(businessId);

  log(`\n=== ${failures === 0 ? 'ALL PASS' : failures + ' FAILURE(S)'} ===\n`);
  await prisma.$disconnect();
  process.exit(failures === 0 ? 0 : 1);
}

main().catch(async (e) => { console.error('FATAL', e); try { await prisma.$disconnect(); } catch (_) {} process.exit(1); });
