// Storefront layout presets: 100 named designs that combine section
// variants into cohesive, industry-shaped looks. Switching presets re-skins the page;
// CMS data (services, team, about, contact) is unchanged.
//
// Architecture:
//   - Each preset has a stable `key`, a human `name`, an `aesthetic`
//     bucket (used by the picker grid grouping), a short description,
//     and a `variants` map { sectionKey: variantKey }.
//   - The storefront looks up the preset by key from
//     subscription.designPreset, then merges in any per-tenant
//     sectionVariants overrides on top.
//   - Variant key 'v1' is reserved across every section as the
//     "Classic" rendering — the look the storefront had before this
//     system existed. Layout 1 ("classic") uses v1 everywhere and is
//     the default for tenants on subscription.designPreset === null.
//
// Adding a new variant:
//   1. Build the variant component in business/app/page.js (the
//      section's variant switch handles the lookup).
//   2. Reference its key in one or more presets here.
//   3. (Optional) Update PRESET_THUMBNAILS for the picker.
//
// This package is the canonical registry. App and backend files should
// re-export it instead of copying preset data.

const LAYOUT_PRESETS = [
  {
    key: 'classic',
    name: 'Classic',
    aesthetic: 'modern',
    description: 'A friendly, balanced layout that works for any business. The default.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'service-front', services: 'service-pathways', about: 'two-col', team: 'v1',
      gallery: 'service-gallery', testimonials: 'service-proof', pricing: 'service-options', faq: 'split-col', contact: 'service-enquiry',
    },
  },
  {
    key: 'magazine',
    name: 'Magazine',
    aesthetic: 'editorial',
    description: 'Editorial vibe — image-heavy hero, masonry services, warm serifs.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'editorial-desk', services: 'editorial-services', about: 'timeline',
      team: 'spotlight', testimonials: 'publication-proof', faq: 'split-col',
      contact: 'editorial-brief', gallery: 'editorial-clips', pricing: 'editorial-packages',
    },
  },
  {
    key: 'minimal-mono',
    name: 'Minimal Mono',
    aesthetic: 'minimal',
    description: 'Typographic, monochrome, single-column. Lets your words do the work.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'about', 'team', 'gallery', 'faq', 'contact'],
    variants: {
      hero: 'service-front', services: 'service-pathways', about: 'quote-card',
      team: 'list', testimonials: 'service-proof', faq: 'numbered',
      contact: 'service-enquiry', gallery: 'service-gallery', pricing: 'service-options',
    },
  },
  {
    key: 'bold-split',
    name: 'Bold Split',
    aesthetic: 'bold',
    description: 'Diagonal split hero, big colour blocks, confident type.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'agency-casebook', services: 'agency-method', about: 'two-col',
      team: 'spotlight', testimonials: 'casebook-proof', faq: 'split-col',
      contact: 'agency-brief', gallery: 'agency-casebook', pricing: 'agency-retainers',
    },
  },
  {
    key: 'wellness-warm',
    name: 'Wellness Warm',
    aesthetic: 'wellness',
    description: 'Soft gradients, generous spacing, rounded everywhere.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'spa-ritual', services: 'ritual-menu', about: 'quote-card',
      team: 'mosaic', testimonials: 'guest-calm-proof', faq: 'split-col',
      contact: 'ritual-booking', gallery: 'ritual-atmosphere', pricing: 'treatment-rituals',
    },
  },
  {
    key: 'tech-grid',
    name: 'Tech Grid',
    aesthetic: 'tech',
    description: 'Dense grid, mono headlines, clinical edges.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'developer-console', services: 'system-builds', about: 'two-col',
      team: 'spotlight', testimonials: 'technical-proof', faq: 'numbered',
      contact: 'technical-brief', gallery: 'system-screens', pricing: 'technical-retainers',
    },
  },
  {
    key: 'luxury-serif',
    name: 'Luxury Serif',
    aesthetic: 'luxury',
    description: 'Wide serif headlines, generous space, refined detail.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'artist-collection', services: 'collection-works', about: 'quote-card',
      team: 'list', testimonials: 'collector-proof', faq: 'split-col',
      contact: 'collector-enquiry', gallery: 'art-collection', pricing: 'art-offers',
    },
  },
  {
    key: 'studio-portfolio',
    name: 'Studio Portfolio',
    aesthetic: 'editorial',
    description: 'Gallery-first. Lets work speak before words.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'portfolio-wall', services: 'case-study-grid', about: 'two-col',
      team: 'mosaic', testimonials: 'project-proof', faq: 'split-col',
      contact: 'project-brief', gallery: 'portfolio-wall', pricing: 'creative-packages',
    },
  },
  {
    key: 'consultancy',
    name: 'Consultancy',
    aesthetic: 'minimal',
    description: 'Text-led, list services, quiet authority.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'diagnostic-room', services: 'diagnostic-offers', about: 'two-col',
      team: 'list', testimonials: 'diagnostic-proof', faq: 'numbered',
      contact: 'diagnostic-brief', gallery: 'diagnostic-workshop', pricing: 'diagnostic-packages',
    },
  },
  {
    key: 'agency-bold',
    name: 'Agency Bold',
    aesthetic: 'bold',
    description: 'Full-bleed hero, bold typography, oversized CTAs.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'agency-casebook', services: 'agency-method', about: 'two-col',
      team: 'mosaic', testimonials: 'casebook-proof', faq: 'split-col',
      contact: 'agency-brief', gallery: 'agency-casebook', pricing: 'agency-retainers',
    },
  },
  {
    key: 'salon-soft',
    name: 'Salon Soft',
    aesthetic: 'wellness',
    description: 'Beauty-salon layout — routine hero, lookbook gallery, kit pricing and a relaxed booking close.',
    sectionOrder: ['services', 'gallery', 'pricing', 'team', 'testimonials', 'about', 'faq', 'contact'],
    variants: {
      hero: 'beauty-routine', services: 'routine-sets', about: 'two-col',
      team: 'carousel', testimonials: 'routine-proof', faq: 'numbered',
      contact: 'routine-advice', gallery: 'routine-shelf', pricing: 'routine-kits',
    },
  },
  {
    key: 'medical-trust',
    name: 'Medical Trust',
    aesthetic: 'modern',
    description: 'Patient-first clinic layout with triage hero, care pathways, clinician proof, visit options and appointment close.',
    sectionOrder: ['services', 'team', 'testimonials', 'pricing', 'about', 'gallery', 'faq', 'contact'],
    variants: {
      hero: 'clinic-intake', services: 'care-pathways', about: 'timeline',
      team: 'spotlight', testimonials: 'patient-proof', faq: 'numbered',
      contact: 'appointment-panel', gallery: 'clinic-tour', pricing: 'visit-options',
    },
  },
  {
    key: 'fitness-energy',
    name: 'Fitness Energy',
    aesthetic: 'bold',
    description: 'Goal-led training layout with sprint hero, program stack, progress proof, coaching plans and goal-check enquiry.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'gallery', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'training-sprint', services: 'program-stack', about: 'two-col',
      team: 'carousel', testimonials: 'progress-proof', faq: 'numbered',
      contact: 'goal-check', gallery: 'training-floor', pricing: 'coaching-plans',
    },
  },
  {
    key: 'restaurant-menu',
    name: 'Restaurant Menu',
    aesthetic: 'editorial',
    description: 'Dining-room layout with menu board, package rail, atmosphere strip, guest proof, and reservation close.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'restaurant-cover', services: 'menu-board', about: 'centered',
      team: 'mosaic', testimonials: 'dining-reviews', faq: 'split-col',
      contact: 'reservation-panel', gallery: 'dining-strip', pricing: 'dining-packages',
    },
  },
  {
    key: 'creative-mosaic',
    name: 'Creative Mosaic',
    aesthetic: 'editorial',
    description: 'Asymmetric grid, playful blocks, expressive type.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'design-casefile', services: 'design-process', about: 'two-col',
      team: 'mosaic', testimonials: 'design-proof', faq: 'numbered',
      contact: 'design-brief', gallery: 'case-study-wall', pricing: 'design-engagements',
    },
  },
  // Archetype presets — these keys are the defaultDesignPreset values the
  // theme catalog (themes/_shared/staticThemes.js) already points at for
  // ~536 themes. Until they existed here, resolvePreset() fell back to
  // 'classic' for all of them, which is why most storefronts looked
  // identical. Each composes a distinct mix of the implemented section
  // variants so the archetypes read differently from each other and from
  // the 15 above.
  {
    key: 'healthcare',
    name: 'Healthcare',
    aesthetic: 'modern',
    description: 'Specialist-practice layout — specialist hero, structured about, reassuring patient voice and specialist options.',
    sectionOrder: ['services', 'about', 'team', 'testimonials', 'pricing', 'gallery', 'faq', 'contact'],
    variants: {
      hero: 'specialist-desk', services: 'specialist-care', about: 'two-col',
      team: 'list', testimonials: 'patient-reassurance', faq: 'split-col',
      contact: 'appointment-request', gallery: 'specialist-suite', pricing: 'specialist-options',
    },
  },
  {
    key: 'academy',
    name: 'Academy',
    aesthetic: 'modern',
    description: 'Education-led — calm centered hero, listed programmes, faces in a mosaic.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'team', 'pricing', 'about', 'faq', 'contact'],
    variants: {
      hero: 'school-open-day', services: 'learning-pathways', about: 'two-col',
      team: 'mosaic', testimonials: 'family-outcomes', faq: 'numbered',
      contact: 'admissions-enquiry', gallery: 'campus-tour', pricing: 'enrolment-options',
    },
  },
  {
    key: 'commerce',
    name: 'Commerce',
    aesthetic: 'bold',
    description: 'Retail-forward — split hero, pricing-table offers, product mosaic, strong CTA.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'retail-drop', services: 'collection-shelf', about: 'centered',
      team: 'mosaic', testimonials: 'buyer-notes', faq: 'split-col',
      contact: 'shop-support', gallery: 'commerce-lookbook', pricing: 'collection-offers',
    },
  },
  {
    key: 'startup',
    name: 'Startup',
    aesthetic: 'tech',
    description: 'Modern SaaS — gradient-mesh hero, accordion features, carousel team, full-width CTA.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'developer-console', services: 'system-builds', about: 'two-col',
      team: 'carousel', testimonials: 'technical-proof', faq: 'split-col',
      contact: 'technical-brief', gallery: 'system-screens', pricing: 'technical-retainers',
    },
  },
  {
    key: 'personal-brand',
    name: 'Personal Brand',
    aesthetic: 'editorial',
    description: 'Solo and expressive — split hero, quote-card about, slideshow gallery, compact contact.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'coach-authority', services: 'coaching-paths', about: 'quote-card',
      team: 'list', testimonials: 'coaching-proof', faq: 'numbered',
      contact: 'coaching-fit', gallery: 'coaching-board', pricing: 'coaching-programs',
    },
  },
  // Premium presets — each leads with one of the new section components
  // (editorial-cover/stat-band/card-stack hero, bento or alternating
  // services, timeline about, spotlight team) so they read as distinct
  // designs, not recolours of the originals.
  {
    key: 'editorial-feature',
    name: 'Editorial Feature',
    aesthetic: 'editorial',
    description: 'Magazine cover hero, alternating feature rows, a spotlighted lead.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'editorial-desk', services: 'editorial-services', about: 'two-col',
      team: 'spotlight', testimonials: 'publication-proof', faq: 'split-col',
      contact: 'editorial-brief', gallery: 'editorial-clips', pricing: 'editorial-packages',
    },
  },
  {
    key: 'bento-modern',
    name: 'Bento Modern',
    aesthetic: 'modern',
    description: 'Stat-band hero, bento services grid, timeline about.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'service-front', services: 'service-pathways', about: 'timeline',
      team: 'mosaic', testimonials: 'service-proof', faq: 'numbered',
      contact: 'service-enquiry', gallery: 'service-gallery', pricing: 'service-options',
    },
  },
  {
    key: 'boutique-card',
    name: 'Boutique Card',
    aesthetic: 'luxury',
    description: 'Layered card-stack hero, masonry services, spotlight lead.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'maker-boutique', services: 'maker-ranges', about: 'quote-card',
      team: 'spotlight', testimonials: 'maker-proof', faq: 'split-col',
      contact: 'custom-order', gallery: 'maker-studio', pricing: 'maker-offers',
    },
  },
  {
    key: 'saas-launch',
    name: 'SaaS Launch',
    aesthetic: 'tech',
    description: 'Stat-band hero, accordion features, timeline, carousel team.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'developer-console', services: 'system-builds', about: 'timeline',
      team: 'carousel', testimonials: 'technical-proof', faq: 'split-col',
      contact: 'technical-brief', gallery: 'system-screens', pricing: 'technical-retainers',
    },
  },
  {
    key: 'studio-feature',
    name: 'Studio Feature',
    aesthetic: 'editorial',
    description: 'Editorial cover, bento work grid, centered story, spotlight lead.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'design-casefile', services: 'design-process', about: 'centered',
      team: 'spotlight', testimonials: 'design-proof', faq: 'numbered',
      contact: 'design-brief', gallery: 'case-study-wall', pricing: 'design-engagements',
    },
  },
  {
    key: 'retail-bento',
    name: 'Retail Bento',
    aesthetic: 'bold',
    description: 'Card-stack hero, bento product grid, strong CTA close.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'retail-drop', services: 'collection-shelf', about: 'two-col',
      team: 'mosaic', testimonials: 'buyer-notes', faq: 'split-col',
      contact: 'shop-support', gallery: 'commerce-lookbook', pricing: 'collection-offers',
    },
  },
  {
    key: 'clinic-timeline',
    name: 'Clinic Timeline',
    aesthetic: 'modern',
    description: 'Journey-led clinic layout — the care timeline leads, with family outcomes, suite gallery and treatment fees.',
    sectionOrder: ['about', 'services', 'team', 'testimonials', 'pricing', 'gallery', 'faq', 'contact'],
    variants: {
      hero: 'clinic-intake', services: 'care-pathways', about: 'timeline',
      team: 'list', testimonials: 'family-outcomes', faq: 'numbered',
      contact: 'appointment-request', gallery: 'dental-suite', pricing: 'treatment-fees',
    },
  },
  {
    key: 'editorial-mono',
    name: 'Editorial Mono',
    aesthetic: 'minimal',
    description: 'Editorial cover with quiet lists and a timeline. Words first.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'editorial-desk', services: 'editorial-services', about: 'timeline',
      team: 'list', testimonials: 'publication-proof', faq: 'numbered',
      contact: 'editorial-brief', gallery: 'editorial-clips', pricing: 'editorial-packages',
    },
  },
  {
    key: 'agency-feature',
    name: 'Agency Feature',
    aesthetic: 'bold',
    description: 'Editorial cover, alternating feature rows, spotlight lead, big CTA.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'agency-casebook', services: 'agency-method', about: 'two-col',
      team: 'spotlight', testimonials: 'casebook-proof', faq: 'split-col',
      contact: 'agency-brief', gallery: 'agency-casebook', pricing: 'agency-retainers',
    },
  },
  {
    key: 'boutique-bento',
    name: 'Boutique Bento',
    aesthetic: 'wellness',
    description: 'Card-stack hero, bento services, quote-card about, soft close.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'beauty-routine', services: 'routine-sets', about: 'quote-card',
      team: 'mosaic', testimonials: 'routine-proof', faq: 'split-col',
      contact: 'routine-advice', gallery: 'routine-shelf', pricing: 'routine-kits',
    },
  },
  {
    key: 'chef-tasting-room',
    name: 'Chef Tasting Room',
    aesthetic: 'luxury',
    description: 'Chef-led dining layout with tasting hero, course-led menu, refined guest proof, tasting offers, chef pass gallery and reservation close.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'chef-table', services: 'tasting-menu', about: 'centered',
      team: 'spotlight', testimonials: 'chef-proof', faq: 'split-col',
      contact: 'tasting-reservation', gallery: 'chef-pass', pricing: 'tasting-offers',
    },
  },
  {
    key: 'cafe-counter',
    name: 'Cafe Counter',
    aesthetic: 'wellness',
    description: 'Warm cafe layout with counter hero, daily shelf services, regular proof, cafe specials, display gallery and order contact.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'cafe-counter-hero', services: 'cafe-shelf', about: 'quote-card',
      team: 'mosaic', testimonials: 'cafe-regulars', faq: 'split-col',
      contact: 'cafe-order', gallery: 'cafe-display', pricing: 'cafe-specials',
    },
  },
  {
    key: 'bar-nightlife',
    name: 'Bar Nightlife',
    aesthetic: 'bold',
    description: 'High-energy venue layout with nightlife hero, bar programs, night proof, table packages, room gallery and booking capture.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'nightlife-stage', services: 'bar-programs', about: 'two-col',
      team: 'carousel', testimonials: 'nightlife-proof', faq: 'numbered',
      contact: 'bar-booking', gallery: 'nightlife-room', pricing: 'bar-packages',
    },
  },
  {
    key: 'food-truck',
    name: 'Food Truck',
    aesthetic: 'modern',
    description: 'Compact mobile food layout with route hero, truck menu, street-food proof, catering options, route gallery and location enquiry.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'truck-route', services: 'truck-menu', about: 'timeline',
      team: 'list', testimonials: 'street-food-proof', faq: 'numbered',
      contact: 'truck-location', gallery: 'truck-route-gallery', pricing: 'truck-catering',
    },
  },
  {
    key: 'private-dining',
    name: 'Private Dining',
    aesthetic: 'luxury',
    description: 'Event-ready restaurant layout with private-room hero, group menus, host proof, room offers, private gallery and qualified enquiry.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'private-room', services: 'private-dining-packages', about: 'quote-card',
      team: 'spotlight', testimonials: 'private-event-proof', faq: 'split-col',
      contact: 'private-dining-enquiry', gallery: 'private-room-gallery', pricing: 'private-room-offers',
    },
  },
  {
    key: 'bakery-display',
    name: 'Bakery Display',
    aesthetic: 'editorial',
    description: 'Product-window bakery layout with bake case hero, tray services, bakery proof, order offers, display gallery and preorder contact.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'bakery-window', services: 'bakery-trays', about: 'centered',
      team: 'mosaic', testimonials: 'bakery-proof', faq: 'split-col',
      contact: 'bakery-order', gallery: 'bakery-case', pricing: 'bakery-offers',
    },
  },
  {
    key: 'catering-events',
    name: 'Catering Events',
    aesthetic: 'modern',
    description: 'Quote-led catering layout with event brief hero, catering packages, host proof, menu options, spread gallery and quote capture.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'catering-brief', services: 'catering-packages', about: 'timeline',
      team: 'spotlight', testimonials: 'catering-proof', faq: 'numbered',
      contact: 'catering-quote', gallery: 'catering-spread', pricing: 'catering-menus',
    },
  },
  {
    key: 'wine-cellar',
    name: 'Wine Cellar',
    aesthetic: 'luxury',
    description: 'Quiet cellar-door layout with tasting hero, cellar tastings, guest proof, memberships, bottle gallery and booking enquiry.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'cellar-door', services: 'cellar-tastings', about: 'quote-card',
      team: 'list', testimonials: 'cellar-proof', faq: 'split-col',
      contact: 'cellar-booking', gallery: 'cellar-gallery', pricing: 'cellar-memberships',
    },
  },
  {
    key: 'dental-clinic',
    name: 'Dental Clinic',
    aesthetic: 'modern',
    description: 'Clean patient-first clinic layout with treatment cards, clinician proof, and booking intent.',
    sectionOrder: ['services', 'team', 'pricing', 'testimonials', 'gallery', 'about', 'faq', 'contact'],
    variants: {
      hero: 'dental-visit', services: 'treatment-grid', about: 'two-col',
      team: 'spotlight', testimonials: 'patient-reassurance', faq: 'numbered',
      contact: 'appointment-request', gallery: 'dental-suite', pricing: 'treatment-fees',
    },
  },
  {
    key: 'therapy-calm',
    name: 'Therapy Calm',
    aesthetic: 'minimal',
    description: 'Soft, confidential layout with therapy hero, support pathways, respectful proof, fee options, calm gallery and fit enquiry.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'gallery', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'therapy-room', services: 'therapy-pathways', about: 'quote-card',
      team: 'list', testimonials: 'therapy-proof', faq: 'split-col',
      contact: 'therapy-enquiry', gallery: 'calm-space', pricing: 'therapy-fees',
    },
  },
  {
    key: 'specialist-practice',
    name: 'Specialist Practice',
    aesthetic: 'editorial',
    description: 'Authority-led specialist layout with referral hero, care pathways, specialist proof, options, suite gallery and referral contact.',
    sectionOrder: ['services', 'team', 'pricing', 'testimonials', 'gallery', 'about', 'faq', 'contact'],
    variants: {
      hero: 'specialist-desk', services: 'specialist-care', about: 'timeline',
      team: 'spotlight', testimonials: 'specialist-proof', faq: 'numbered',
      contact: 'specialist-referral', gallery: 'specialist-suite', pricing: 'specialist-options',
    },
  },
  {
    key: 'diagnostic-lab',
    name: 'Diagnostic Lab',
    aesthetic: 'tech',
    description: 'Precise diagnostic layout with specialist hero, care pathways, referral proof, diagnostic options, suite gallery and referral contact.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'gallery', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'specialist-desk', services: 'specialist-care', about: 'two-col',
      team: 'v1', testimonials: 'specialist-proof', faq: 'numbered',
      contact: 'specialist-referral', gallery: 'specialist-suite', pricing: 'specialist-options',
    },
  },
  {
    key: 'veterinary-care',
    name: 'Veterinary Care',
    aesthetic: 'modern',
    description: 'Warm veterinary layout with pet visit hero, care pathways, family proof, pet care plans, clinic tour and visit request.',
    sectionOrder: ['services', 'team', 'pricing', 'testimonials', 'gallery', 'about', 'faq', 'contact'],
    variants: {
      hero: 'vet-visit', services: 'pet-care-pathways', about: 'centered',
      team: 'mosaic', testimonials: 'pet-family-proof', faq: 'split-col',
      contact: 'pet-visit-request', gallery: 'pet-clinic-tour', pricing: 'pet-care-plans',
    },
  },
  {
    key: 'spa-retreat',
    name: 'Spa Retreat',
    aesthetic: 'wellness',
    description: 'Calm, gallery-led spa retreat — atmosphere first, treatment grid, centred story and treatment-fee pricing.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'spa-ritual', services: 'treatment-grid', about: 'centered',
      team: 'spotlight', testimonials: 'guest-calm-proof', faq: 'split-col',
      contact: 'ritual-booking', gallery: 'calm-space', pricing: 'treatment-fees',
    },
  },
  {
    key: 'skincare-clinic',
    name: 'Skincare Clinic',
    aesthetic: 'luxury',
    description: 'Premium skincare layout with beauty routine hero, routine services, product/treatment proof, routine kits, shelf gallery and advice panel.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'beauty-routine', services: 'routine-sets', about: 'two-col',
      team: 'spotlight', testimonials: 'routine-proof', faq: 'numbered',
      contact: 'routine-advice', gallery: 'routine-shelf', pricing: 'routine-kits',
    },
  },
  {
    key: 'barber-shop',
    name: 'Barber Shop',
    aesthetic: 'bold',
    description: 'Sharp grooming layout with service lists, maker profiles, lookbook proof, and booking CTA.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'barber-chair', services: 'grooming-menu', about: 'centered',
      team: 'mosaic', testimonials: 'chair-proof', faq: 'numbered',
      contact: 'chair-booking', gallery: 'barber-lookbook', pricing: 'grooming-packages',
    },
  },
  {
    key: 'yoga-studio',
    name: 'Yoga Studio',
    aesthetic: 'wellness',
    description: 'Class-led studio layout with coaching authority hero, practice pathways, member proof, programs, studio board gallery and fit enquiry.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'coach-authority', services: 'coaching-paths', about: 'timeline',
      team: 'list', testimonials: 'coaching-proof', faq: 'split-col',
      contact: 'coaching-fit', gallery: 'coaching-board', pricing: 'coaching-programs',
    },
  },
  {
    key: 'wellness-coach',
    name: 'Wellness Coach',
    aesthetic: 'minimal',
    description: 'Personal support layout with authority hero, coaching paths, client proof, program options, coaching board and fit enquiry.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'gallery', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'coach-authority', services: 'coaching-paths', about: 'quote-card',
      team: 'list', testimonials: 'coaching-proof', faq: 'numbered',
      contact: 'coaching-fit', gallery: 'coaching-board', pricing: 'coaching-programs',
    },
  },
  {
    key: 'fitness-program',
    name: 'Fitness Program',
    aesthetic: 'bold',
    description: 'Action-first training layout with sprint hero, program stack, progress proof, coaching plans, training floor gallery and goal check.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'training-sprint', services: 'program-stack', about: 'timeline',
      team: 'carousel', testimonials: 'progress-proof', faq: 'numbered',
      contact: 'goal-check', gallery: 'training-floor', pricing: 'coaching-plans',
    },
  },
  {
    key: 'maternity-care',
    name: 'Maternity Care',
    aesthetic: 'wellness',
    description: 'Gentle care layout with clinic intake hero, care pathways, patient proof, visit options, clinic tour and appointment request.',
    sectionOrder: ['services', 'team', 'pricing', 'testimonials', 'gallery', 'about', 'faq', 'contact'],
    variants: {
      hero: 'clinic-intake', services: 'care-pathways', about: 'centered',
      team: 'spotlight', testimonials: 'patient-proof', faq: 'split-col',
      contact: 'appointment-panel', gallery: 'clinic-tour', pricing: 'visit-options',
    },
  },
  {
    key: 'school-prospectus',
    name: 'School Prospectus',
    aesthetic: 'editorial',
    description: 'Open-day style school layout with programs, outcomes, faculty, and campus imagery.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'team', 'pricing', 'about', 'faq', 'contact'],
    variants: {
      hero: 'school-open-day', services: 'learning-pathways', about: 'timeline',
      team: 'mosaic', testimonials: 'family-outcomes', faq: 'numbered',
      contact: 'admissions-enquiry', gallery: 'campus-tour', pricing: 'enrolment-options',
    },
  },
  {
    key: 'tutor-conversion',
    name: 'Tutor Conversion',
    aesthetic: 'minimal',
    description: 'Assessment-led tutoring layout with subject pathways, learning outcomes, packages, learning-space gallery and enquiry capture.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'gallery', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'tutor-plan', services: 'subject-pathways', about: 'two-col',
      team: 'list', testimonials: 'learning-outcomes', faq: 'numbered',
      contact: 'assessment-enquiry', gallery: 'learning-space', pricing: 'tutoring-packages',
    },
  },
  {
    key: 'course-launch',
    name: 'Course Launch',
    aesthetic: 'tech',
    description: 'Cohort launch layout with module stack, student proof, cohort options, course assets and enrolment enquiry.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'team', 'gallery', 'about', 'faq', 'contact'],
    variants: {
      hero: 'course-launchpad', services: 'module-stack', about: 'timeline',
      team: 'spotlight', testimonials: 'cohort-proof', faq: 'split-col',
      contact: 'cohort-enquiry', gallery: 'course-assets', pricing: 'cohort-options',
    },
  },
  {
    key: 'cohort-academy',
    name: 'Cohort Academy',
    aesthetic: 'modern',
    description: 'Structured cohort layout with launchpad hero, module stack, cohort proof, options, course assets and cohort enquiry.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'team', 'gallery', 'about', 'faq', 'contact'],
    variants: {
      hero: 'course-launchpad', services: 'module-stack', about: 'quote-card',
      team: 'carousel', testimonials: 'cohort-proof', faq: 'numbered',
      contact: 'cohort-enquiry', gallery: 'course-assets', pricing: 'cohort-options',
    },
  },
  {
    key: 'preschool-warm',
    name: 'Preschool Warm',
    aesthetic: 'wellness',
    description: 'Family-friendly early learning layout with open-day hero, learning pathways, family proof, enrolment options and campus tour.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'team', 'pricing', 'about', 'faq', 'contact'],
    variants: {
      hero: 'school-open-day', services: 'learning-pathways', about: 'centered',
      team: 'mosaic', testimonials: 'family-outcomes', faq: 'split-col',
      contact: 'admissions-enquiry', gallery: 'campus-tour', pricing: 'enrolment-options',
    },
  },
  {
    key: 'language-institute',
    name: 'Language Institute',
    aesthetic: 'editorial',
    description: 'Program-led language institute layout with assessment hero, subject pathways, learning proof, tutoring packages and placement enquiry.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'gallery', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'tutor-plan', services: 'subject-pathways', about: 'timeline',
      team: 'spotlight', testimonials: 'learning-outcomes', faq: 'split-col',
      contact: 'assessment-enquiry', gallery: 'learning-space', pricing: 'tutoring-packages',
    },
  },
  {
    key: 'training-enterprise',
    name: 'Training Enterprise',
    aesthetic: 'tech',
    description: 'B2B training layout for capability programs, delivery models, proof, and sales enquiries.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'team', 'gallery', 'about', 'faq', 'contact'],
    variants: {
      hero: 'course-launchpad', services: 'module-stack', about: 'two-col',
      team: 'list', testimonials: 'cohort-proof', faq: 'numbered',
      contact: 'cohort-enquiry', gallery: 'course-assets', pricing: 'cohort-options',
    },
  },
  {
    key: 'law-prestige',
    name: 'Law Prestige',
    aesthetic: 'luxury',
    description: 'High-trust legal layout with matter brief hero, practice dossiers, client evidence, scoped engagements and confidential intake.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'team', 'about', 'gallery', 'faq', 'contact'],
    variants: {
      hero: 'legal-brief', services: 'practice-dossier', about: 'two-col',
      team: 'spotlight', testimonials: 'client-evidence', faq: 'split-col',
      contact: 'confidential-intake', gallery: 'firm-library', pricing: 'engagement-scope',
    },
  },
  {
    key: 'accounting-trust',
    name: 'Accounting Trust',
    aesthetic: 'minimal',
    description: 'Document-led finance layout with ledger hero, advisory services, confidence proof, retainers and secure intake.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'team', 'about', 'gallery', 'faq', 'contact'],
    variants: {
      hero: 'finance-ledger', services: 'ledger-services', about: 'timeline',
      team: 'list', testimonials: 'finance-confidence', faq: 'numbered',
      contact: 'document-intake', gallery: 'document-stack', pricing: 'advisory-retainers',
    },
  },
  {
    key: 'finance-advisor',
    name: 'Finance Advisor',
    aesthetic: 'editorial',
    description: 'Advice-led planning layout with goal intake, planning pathways, advisor proof, retainers and document-ready contact.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'team', 'about', 'gallery', 'faq', 'contact'],
    variants: {
      hero: 'advisor-plan', services: 'planning-pathways', about: 'quote-card',
      team: 'spotlight', testimonials: 'advisor-confidence', faq: 'split-col',
      contact: 'planning-intake', gallery: 'planning-desk', pricing: 'planning-retainers',
    },
  },
  {
    key: 'immigration-pathway',
    name: 'Immigration Pathway',
    aesthetic: 'modern',
    description: 'Visa pathway layout with eligibility hero, visa stages, applicant proof, visa options and assessment contact.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'visa-pathway', services: 'visa-stages', about: 'timeline',
      team: 'list', testimonials: 'visa-confidence', faq: 'numbered',
      contact: 'visa-assessment', gallery: 'visa-documents', pricing: 'visa-options',
    },
  },
  {
    key: 'consultant-diagnostic',
    name: 'Consultant Diagnostic',
    aesthetic: 'tech',
    description: 'Diagnostic consulting layout with problem-framing hero, diagnostic offers, proof, packages and brief capture.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'diagnostic-room', services: 'diagnostic-offers', about: 'two-col',
      team: 'carousel', testimonials: 'diagnostic-proof', faq: 'split-col',
      contact: 'diagnostic-brief', gallery: 'diagnostic-workshop', pricing: 'diagnostic-packages',
    },
  },
  {
    key: 'recruitment-board',
    name: 'Recruitment Board',
    aesthetic: 'bold',
    description: 'Hiring-desk layout for role briefs, recruitment pathways, hiring proof, retainers, pipeline gallery and employer enquiry.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'recruitment-desk', services: 'hiring-board', about: 'centered',
      team: 'mosaic', testimonials: 'hiring-proof', faq: 'split-col',
      contact: 'hiring-brief', gallery: 'pipeline-board', pricing: 'hiring-retainers',
    },
  },
  {
    key: 'notary-simple',
    name: 'Notary Simple',
    aesthetic: 'minimal',
    description: 'Fast document-service layout with notary counter hero, document tasks, proof, fees and appointment prep.',
    sectionOrder: ['services', 'pricing', 'testimonials', 'gallery', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'notary-counter', services: 'document-tasks', about: 'v1',
      team: 'list', testimonials: 'document-proof', faq: 'numbered',
      contact: 'document-appointment', gallery: 'notary-documents', pricing: 'notary-fees',
    },
  },
  {
    key: 'corporate-boardroom',
    name: 'Corporate Boardroom',
    aesthetic: 'modern',
    description: 'Executive decision-support layout with boardroom hero, advisory workstreams, proof, retainers, artefact gallery and intake.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'boardroom-brief', services: 'boardroom-services', about: 'two-col',
      team: 'spotlight', testimonials: 'executive-proof', faq: 'split-col',
      contact: 'boardroom-intake', gallery: 'boardroom-table', pricing: 'executive-retainers',
    },
  },
  {
    key: 'real-estate-showcase',
    name: 'Real Estate Showcase',
    aesthetic: 'modern',
    description: 'Property-first layout with appraisal intent, listing pathways, inspection proof, property tour, and enquiry capture.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'property-showcase', services: 'property-pathways', about: 'centered',
      team: 'mosaic', testimonials: 'seller-buyer-proof', faq: 'split-col',
      contact: 'appraisal-request', gallery: 'property-tour', pricing: 'property-options',
    },
  },
  {
    key: 'architect-portfolio',
    name: 'Architect Portfolio',
    aesthetic: 'editorial',
    description: 'Commission-ready architecture layout with studio hero, project archive, commission paths, proof, options and brief capture.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'architecture-studio', services: 'studio-commissions', about: 'quote-card',
      team: 'spotlight', testimonials: 'commission-proof', faq: 'numbered',
      contact: 'commission-brief', gallery: 'architecture-projects', pricing: 'commission-options',
    },
  },
  {
    key: 'builder-projects',
    name: 'Builder Projects',
    aesthetic: 'bold',
    description: 'Quote-ready construction layout with site hero, build capabilities, progress gallery, proof, packages and project quote.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'builder-site', services: 'build-capabilities', about: 'timeline',
      team: 'list', testimonials: 'build-proof', faq: 'numbered',
      contact: 'project-quote', gallery: 'site-progress', pricing: 'build-packages',
    },
  },
  {
    key: 'interior-lookbook',
    name: 'Interior Lookbook',
    aesthetic: 'luxury',
    description: 'Image-led interior design layout with room lookbook, schemes, design packages, proof and room brief capture.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'interior-lookbook', services: 'room-schemes', about: 'centered',
      team: 'spotlight', testimonials: 'room-proof', faq: 'split-col',
      contact: 'room-brief', gallery: 'interior-rooms', pricing: 'design-packages',
    },
  },
  {
    key: 'landscaping-before-after',
    name: 'Landscaping Before After',
    aesthetic: 'wellness',
    description: 'Outdoor project layout with site-visit hero, outdoor service paths, yard proof, landscape packages, before-after gallery and quote capture.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'landscape-plan', services: 'outdoor-projects', about: 'timeline',
      team: 'mosaic', testimonials: 'yard-proof', faq: 'numbered',
      contact: 'landscape-quote', gallery: 'outdoor-before-after', pricing: 'landscape-packages',
    },
  },
  {
    key: 'trades-quote',
    name: 'Trades Quote',
    aesthetic: 'tech',
    description: 'Dispatch-board layout for trades, urgent jobs, estimates, before-after proof, service plans, and quote capture.',
    sectionOrder: ['services', 'testimonials', 'gallery', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'trade-dispatch', services: 'trade-quote-board', about: 'two-col',
      team: 'list', testimonials: 'local-job-proof', faq: 'numbered',
      contact: 'quote-dispatch', gallery: 'before-after', pricing: 'service-plans',
    },
  },
  {
    key: 'cleaning-service',
    name: 'Cleaning Service',
    aesthetic: 'modern',
    description: 'Cleaning-service layout with route hero, cleaning plans, clean proof, recurring packages, results gallery and quote capture.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'cleaning-route', services: 'cleaning-plans', about: 'centered',
      team: 'mosaic', testimonials: 'clean-proof', faq: 'split-col',
      contact: 'cleaning-quote', gallery: 'cleaning-results', pricing: 'cleaning-packages',
    },
  },
  {
    key: 'home-maintenance',
    name: 'Home Maintenance',
    aesthetic: 'minimal',
    description: 'Reliable maintenance layout with repair-log hero, repair checklist, home proof, maintenance plans and request capture.',
    sectionOrder: ['services', 'testimonials', 'pricing', 'gallery', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'maintenance-log', services: 'repair-checklist', about: 'timeline',
      team: 'list', testimonials: 'home-proof', faq: 'numbered',
      contact: 'maintenance-request', gallery: 'repair-log', pricing: 'maintenance-plans',
    },
  },
  {
    key: 'photographer-gallery',
    name: 'Photographer Gallery',
    aesthetic: 'editorial',
    description: 'Portfolio-wall layout for selected work, case-study services, project proof, creative packages and brief capture.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'portfolio-wall', services: 'case-study-grid', about: 'quote-card',
      team: 'list', testimonials: 'project-proof', faq: 'split-col',
      contact: 'project-brief', gallery: 'portfolio-wall', pricing: 'creative-packages',
    },
  },
  {
    key: 'writer-editorial',
    name: 'Writer Editorial',
    aesthetic: 'minimal',
    description: 'Text-first portfolio for writers and editors with editorial-desk hero, service paths, publication proof, clips and brief capture.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'editorial-desk', services: 'editorial-services', about: 'quote-card',
      team: 'list', testimonials: 'publication-proof', faq: 'numbered',
      contact: 'editorial-brief', gallery: 'editorial-clips', pricing: 'editorial-packages',
    },
  },
  {
    key: 'developer-systems',
    name: 'Developer Systems',
    aesthetic: 'tech',
    description: 'Systems/ops layout — capability hero, capability matrix, operations proof, pipeline gallery and scoped engagements.',
    sectionOrder: ['services', 'testimonials', 'gallery', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'industrial-capability', services: 'capability-matrix', about: 'two-col',
      team: 'list', testimonials: 'operations-proof', faq: 'numbered',
      contact: 'technical-brief', gallery: 'pipeline-board', pricing: 'engagement-scope',
    },
  },
  {
    key: 'designer-case-study',
    name: 'Designer Case Study',
    aesthetic: 'editorial',
    description: 'Case-study-led design layout with casefile hero, design process, proof, engagements, visual case wall and design brief.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'design-casefile', services: 'design-process', about: 'two-col',
      team: 'spotlight', testimonials: 'design-proof', faq: 'numbered',
      contact: 'design-brief', gallery: 'case-study-wall', pricing: 'design-engagements',
    },
  },
  {
    key: 'creator-channel',
    name: 'Creator Channel',
    aesthetic: 'bold',
    description: 'Audience-first creator layout with channel hero, creator offers, audience proof, packages, channel assets and collaboration brief.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'creator-studio', services: 'creator-offers', about: 'centered',
      team: 'mosaic', testimonials: 'audience-proof', faq: 'split-col',
      contact: 'collaboration-brief', gallery: 'channel-assets', pricing: 'creator-packages',
    },
  },
  {
    key: 'podcast-studio',
    name: 'Podcast Studio',
    aesthetic: 'editorial',
    description: 'Media layout for shows with studio hero, production paths, listener proof, episode library, packages and episode brief capture.',
    sectionOrder: ['gallery', 'services', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'podcast-studio', services: 'show-production', about: 'quote-card',
      team: 'mosaic', testimonials: 'listener-proof', faq: 'numbered',
      contact: 'episode-brief', gallery: 'episode-library', pricing: 'production-packages',
    },
  },
  {
    key: 'speaker-stage',
    name: 'Speaker Stage',
    aesthetic: 'bold',
    description: 'Keynote and performer layout with stage hero, talk topics, event proof, speaking packages, stage reel and booking brief.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'speaker-stage', services: 'talk-topics', about: 'timeline',
      team: 'spotlight', testimonials: 'stage-proof', faq: 'split-col',
      contact: 'speaking-brief', gallery: 'stage-reel', pricing: 'speaking-packages',
    },
  },
  {
    key: 'coach-authority',
    name: 'Coach Authority',
    aesthetic: 'minimal',
    description: 'Speaker/authority stage layout — stage hero, talk topics, stage proof, speaking packages and a speaking brief.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'speaker-stage', services: 'talk-topics', about: 'quote-card',
      team: 'spotlight', testimonials: 'stage-proof', faq: 'split-col',
      contact: 'speaking-brief', gallery: 'stage-reel', pricing: 'speaking-packages',
    },
  },
  {
    key: 'artist-collection',
    name: 'Artist Collection',
    aesthetic: 'luxury',
    description: 'Collection-led artist layout with collection hero, works, collector proof, art offers, collection wall and collector enquiry.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'artist-collection', services: 'collection-works', about: 'centered',
      team: 'list', testimonials: 'collector-proof', faq: 'split-col',
      contact: 'collector-enquiry', gallery: 'art-collection', pricing: 'art-offers',
    },
  },
  {
    key: 'agency-casebook',
    name: 'Agency Casebook',
    aesthetic: 'bold',
    description: 'Proof-led agency layout with casebook hero, method services, proof, retainers, gallery and growth brief.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'agency-casebook', services: 'agency-method', about: 'two-col',
      team: 'spotlight', testimonials: 'casebook-proof', faq: 'split-col',
      contact: 'agency-brief', gallery: 'agency-casebook', pricing: 'agency-retainers',
    },
  },
  {
    key: 'fashion-drop',
    name: 'Fashion Drop',
    aesthetic: 'luxury',
    description: 'Launch-style retail layout with drop hero, collection shelf, buyer notes, lookbook, offers and shop support.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'retail-drop', services: 'collection-shelf', about: 'quote-card',
      team: 'mosaic', testimonials: 'buyer-notes', faq: 'split-col',
      contact: 'shop-support', gallery: 'commerce-lookbook', pricing: 'collection-offers',
    },
  },
  {
    key: 'grocery-market',
    name: 'Grocery Market',
    aesthetic: 'modern',
    description: 'Fresh local retail layout with market hero, seasonal product groups, fresh proof, boxes, shelf gallery and order enquiry.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'market-stall', services: 'market-groups', about: 'centered',
      team: 'v1', testimonials: 'fresh-proof', faq: 'split-col',
      contact: 'market-order', gallery: 'market-shelves', pricing: 'market-boxes',
    },
  },
  {
    key: 'electronics-catalog',
    name: 'Electronics Catalog',
    aesthetic: 'tech',
    description: 'Structured electronics layout with spec hero, product categories, buyer support proof, bundles, spec gallery and advice capture.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'spec-catalog', services: 'spec-categories', about: 'two-col',
      team: 'v1', testimonials: 'buyer-support-proof', faq: 'numbered',
      contact: 'product-advice', gallery: 'product-specs', pricing: 'product-bundles',
    },
  },
  {
    key: 'furniture-showroom',
    name: 'Furniture Showroom',
    aesthetic: 'luxury',
    description: 'Showroom layout with room-fit hero, room collections, showroom proof, packages, room gallery and visit enquiry.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'showroom-floor', services: 'room-collections', about: 'centered',
      team: 'spotlight', testimonials: 'showroom-proof', faq: 'split-col',
      contact: 'showroom-visit', gallery: 'showroom-rooms', pricing: 'showroom-packages',
    },
  },
  {
    key: 'beauty-brand-store',
    name: 'Beauty Brand Store',
    aesthetic: 'wellness',
    description: 'Brand-led beauty retail layout with routine hero, product sets, routine proof, kits, shelf gallery and advice capture.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'beauty-routine', services: 'routine-sets', about: 'quote-card',
      team: 'mosaic', testimonials: 'routine-proof', faq: 'split-col',
      contact: 'routine-advice', gallery: 'routine-shelf', pricing: 'routine-kits',
    },
  },
  {
    key: 'subscription-box',
    name: 'Subscription Box',
    aesthetic: 'bold',
    description: 'Recurring-offer layout with subscription hero, box plans, subscriber proof, box subscriptions, unboxing gallery and support capture.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'subscription-unbox', services: 'box-plans', about: 'timeline',
      team: 'v1', testimonials: 'subscriber-proof', faq: 'numbered',
      contact: 'subscription-help', gallery: 'box-unboxing', pricing: 'box-subscriptions',
    },
  },
  {
    key: 'wholesale-catalog',
    name: 'Wholesale Catalog',
    aesthetic: 'minimal',
    description: 'B2B catalog layout with trade hero, wholesale ranges, trade proof, terms, catalog gallery and account enquiry.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'wholesale-desk', services: 'trade-ranges', about: 'two-col',
      team: 'v1', testimonials: 'trade-proof', faq: 'split-col',
      contact: 'trade-account', gallery: 'trade-catalog', pricing: 'trade-terms',
    },
  },
  {
    key: 'handmade-boutique',
    name: 'Handmade Boutique',
    aesthetic: 'editorial',
    description: 'Craft retail layout with maker hero, handmade ranges, maker proof, offers, studio gallery and custom order capture.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'maker-boutique', services: 'maker-ranges', about: 'centered',
      team: 'mosaic', testimonials: 'maker-proof', faq: 'split-col',
      contact: 'custom-order', gallery: 'maker-studio', pricing: 'maker-offers',
    },
  },
  {
    key: 'wedding-venue',
    name: 'Wedding Venue',
    aesthetic: 'luxury',
    description: 'Romantic venue layout with celebration hero, venue packages, celebration proof, spaces gallery and date-check capture.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'venue-celebration', services: 'venue-packages', about: 'quote-card',
      team: 'spotlight', testimonials: 'celebration-proof', faq: 'split-col',
      contact: 'venue-date-check', gallery: 'venue-spaces', pricing: 'venue-packages',
    },
  },
  {
    key: 'event-planner',
    name: 'Event Planner',
    aesthetic: 'bold',
    description: 'Production-led event layout with command hero, planning blueprint, event proof, package options, production gallery and brief CTA.',
    sectionOrder: ['services', 'pricing', 'gallery', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'event-command', services: 'event-blueprint', about: 'timeline',
      team: 'mosaic', testimonials: 'event-proof', faq: 'numbered',
      contact: 'event-brief', gallery: 'event-production', pricing: 'event-packages',
    },
  },
  {
    key: 'hotel-resort',
    name: 'Hotel Resort',
    aesthetic: 'luxury',
    description: 'Stay-led hospitality layout with room finder hero, amenities, guest reviews, room offers, stay gallery and enquiry panel.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'team', 'about', 'faq', 'contact'],
    variants: {
      hero: 'hotel-stay', services: 'stay-amenities', about: 'centered',
      team: 'mosaic', testimonials: 'stay-reviews', faq: 'split-col',
      contact: 'stay-enquiry', gallery: 'stay-gallery', pricing: 'room-offers',
    },
  },
  {
    key: 'travel-experiences',
    name: 'Travel Experiences',
    aesthetic: 'editorial',
    description: 'Story-rich travel layout with journey hero, itinerary paths, traveller proof, trip options, travel scenes and custom enquiry.',
    sectionOrder: ['gallery', 'services', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'journey-map', services: 'itinerary-paths', about: 'timeline',
      team: 'spotlight', testimonials: 'traveller-proof', faq: 'numbered',
      contact: 'trip-enquiry', gallery: 'travel-scenes', pricing: 'trip-options',
    },
  },
  {
    key: 'nonprofit-cause',
    name: 'Nonprofit Cause',
    aesthetic: 'modern',
    description: 'Cause-first layout with impact hero, program pathways, supporter proof, donation paths, story gallery and action contact.',
    sectionOrder: ['services', 'gallery', 'pricing', 'testimonials', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'cause-impact', services: 'impact-programs', about: 'two-col',
      team: 'mosaic', testimonials: 'impact-proof', faq: 'split-col',
      contact: 'supporter-action', gallery: 'cause-stories', pricing: 'donation-paths',
    },
  },
  {
    key: 'community-hub',
    name: 'Community Hub',
    aesthetic: 'wellness',
    description: 'Accessible community layout with welcome hero, community programs, member proof, participation options and moments gallery.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'community-welcome', services: 'community-programs', about: 'centered',
      team: 'mosaic', testimonials: 'member-proof', faq: 'split-col',
      contact: 'participation-enquiry', gallery: 'community-moments', pricing: 'membership-options',
    },
  },
  {
    key: 'church-ministry',
    name: 'Church Ministry',
    aesthetic: 'minimal',
    description: 'Calm ministry layout with gathering hero, ministry pathways, visitor proof, giving/group options, life gallery and visit details.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'ministry-gathering', services: 'ministry-pathways', about: 'quote-card',
      team: 'list', testimonials: 'ministry-proof', faq: 'numbered',
      contact: 'visit-ministry', gallery: 'ministry-life', pricing: 'ministry-giving',
    },
  },
  {
    key: 'industrial-capability',
    name: 'Industrial Capability',
    aesthetic: 'tech',
    description: 'Operational B2B layout with capability hero, matrix services, operations proof, capacity options and sales brief capture.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'industrial-capability', services: 'capability-matrix', about: 'timeline',
      team: 'list', testimonials: 'operations-proof', faq: 'numbered',
      contact: 'sales-brief', gallery: 'factory-floor', pricing: 'capacity-options',
    },
  },
  {
    key: 'logistics-network',
    name: 'Logistics Network',
    aesthetic: 'modern',
    description: 'Route-first logistics layout with lane network, delivery proof, freight options, network map and quote-ready contact.',
    sectionOrder: ['services', 'gallery', 'testimonials', 'pricing', 'about', 'team', 'faq', 'contact'],
    variants: {
      hero: 'logistics-network', services: 'lane-network', about: 'two-col',
      team: 'v1', testimonials: 'delivery-proof', faq: 'numbered',
      contact: 'freight-quote', gallery: 'network-map', pricing: 'freight-options',
    },
  },
];

const PRESETS_BY_KEY = Object.fromEntries(LAYOUT_PRESETS.map((p) => [p.key, p]));

// Variants the storefront can render per section. The picker UI uses
// these lists to populate per-section dropdowns when an admin wants to
// override a preset's defaults. Keep in lockstep with the section
// dispatchers in business/app/page.js — adding a variant here without
// implementing it makes the dispatcher fall back to v1 silently
// (harmless but wastes the admin's selection).
const AVAILABLE_VARIANTS = {
  hero:        ['v1', 'split-image', 'minimal-centered', 'gradient-mesh', 'stat-band', 'editorial-split', 'card-stack', 'restaurant-cover', 'clinic-intake', 'legal-brief', 'training-sprint', 'barber-chair', 'dental-visit', 'school-open-day', 'property-showcase', 'trade-dispatch', 'retail-drop', 'portfolio-wall', 'finance-ledger', 'spa-ritual', 'hotel-stay', 'industrial-capability', 'tutor-plan', 'course-launchpad', 'recruitment-desk', 'logistics-network', 'advisor-plan', 'visa-pathway', 'diagnostic-room', 'notary-counter', 'boardroom-brief', 'architecture-studio', 'builder-site', 'interior-lookbook', 'landscape-plan', 'cleaning-route', 'maintenance-log', 'editorial-desk', 'developer-console', 'design-casefile', 'creator-studio', 'podcast-studio', 'speaker-stage', 'coach-authority', 'artist-collection', 'agency-casebook', 'market-stall', 'spec-catalog', 'showroom-floor', 'beauty-routine', 'subscription-unbox', 'wholesale-desk', 'maker-boutique', 'venue-celebration', 'event-command', 'journey-map', 'cause-impact', 'community-welcome', 'ministry-gathering', 'chef-table', 'cafe-counter-hero', 'nightlife-stage', 'truck-route', 'private-room', 'bakery-window', 'catering-brief', 'cellar-door', 'therapy-room', 'specialist-desk', 'vet-visit', 'service-front'],
  services:    ['v1', 'masonry', 'list', 'accordion', 'pricing-table', 'bento-grid', 'alternating-rows', 'menu-board', 'care-pathways', 'practice-dossier', 'program-stack', 'grooming-menu', 'treatment-grid', 'learning-pathways', 'property-pathways', 'trade-quote-board', 'collection-shelf', 'case-study-grid', 'ledger-services', 'ritual-menu', 'stay-amenities', 'capability-matrix', 'subject-pathways', 'module-stack', 'hiring-board', 'lane-network', 'planning-pathways', 'visa-stages', 'diagnostic-offers', 'document-tasks', 'boardroom-services', 'studio-commissions', 'build-capabilities', 'room-schemes', 'outdoor-projects', 'cleaning-plans', 'repair-checklist', 'editorial-services', 'system-builds', 'design-process', 'creator-offers', 'show-production', 'talk-topics', 'coaching-paths', 'collection-works', 'agency-method', 'market-groups', 'spec-categories', 'room-collections', 'routine-sets', 'box-plans', 'trade-ranges', 'maker-ranges', 'venue-packages', 'event-blueprint', 'itinerary-paths', 'impact-programs', 'community-programs', 'ministry-pathways', 'tasting-menu', 'cafe-shelf', 'bar-programs', 'truck-menu', 'private-dining-packages', 'bakery-trays', 'catering-packages', 'cellar-tastings', 'therapy-pathways', 'specialist-care', 'pet-care-pathways', 'service-pathways'],
  about:       ['v1', 'quote-card', 'two-col', 'centered', 'timeline'],
  team:        ['v1', 'mosaic', 'list', 'carousel', 'spotlight'],
  testimonials:['v1', 'quote-rail', 'single-spotlight', 'dining-reviews', 'patient-proof', 'client-evidence', 'progress-proof', 'chair-proof', 'patient-reassurance', 'family-outcomes', 'seller-buyer-proof', 'local-job-proof', 'buyer-notes', 'project-proof', 'finance-confidence', 'guest-calm-proof', 'stay-reviews', 'operations-proof', 'learning-outcomes', 'cohort-proof', 'hiring-proof', 'delivery-proof', 'advisor-confidence', 'visa-confidence', 'diagnostic-proof', 'document-proof', 'executive-proof', 'commission-proof', 'build-proof', 'room-proof', 'yard-proof', 'clean-proof', 'home-proof', 'publication-proof', 'technical-proof', 'design-proof', 'audience-proof', 'listener-proof', 'stage-proof', 'coaching-proof', 'collector-proof', 'casebook-proof', 'fresh-proof', 'buyer-support-proof', 'showroom-proof', 'routine-proof', 'subscriber-proof', 'trade-proof', 'maker-proof', 'celebration-proof', 'event-proof', 'traveller-proof', 'impact-proof', 'member-proof', 'ministry-proof', 'chef-proof', 'cafe-regulars', 'nightlife-proof', 'street-food-proof', 'private-event-proof', 'bakery-proof', 'catering-proof', 'cellar-proof', 'therapy-proof', 'specialist-proof', 'pet-family-proof', 'service-proof'],
  gallery:     ['v1', 'mosaic', 'slideshow', 'dining-strip', 'clinic-tour', 'firm-library', 'training-floor', 'barber-lookbook', 'dental-suite', 'campus-tour', 'property-tour', 'before-after', 'commerce-lookbook', 'portfolio-wall', 'document-stack', 'ritual-atmosphere', 'stay-gallery', 'factory-floor', 'learning-space', 'course-assets', 'pipeline-board', 'network-map', 'planning-desk', 'visa-documents', 'diagnostic-workshop', 'notary-documents', 'boardroom-table', 'architecture-projects', 'site-progress', 'interior-rooms', 'outdoor-before-after', 'cleaning-results', 'repair-log', 'editorial-clips', 'system-screens', 'case-study-wall', 'channel-assets', 'episode-library', 'stage-reel', 'coaching-board', 'art-collection', 'agency-casebook', 'market-shelves', 'product-specs', 'showroom-rooms', 'routine-shelf', 'box-unboxing', 'trade-catalog', 'maker-studio', 'venue-spaces', 'event-production', 'travel-scenes', 'cause-stories', 'community-moments', 'ministry-life', 'chef-pass', 'cafe-display', 'nightlife-room', 'truck-route-gallery', 'private-room-gallery', 'bakery-case', 'catering-spread', 'cellar-gallery', 'calm-space', 'specialist-suite', 'pet-clinic-tour', 'service-gallery'],
  faq:         ['v1', 'numbered', 'split-col'],
  contact:     ['v1', 'cta-bar', 'compact', 'reservation-panel', 'appointment-panel', 'confidential-intake', 'goal-check', 'chair-booking', 'appointment-request', 'admissions-enquiry', 'appraisal-request', 'quote-dispatch', 'shop-support', 'project-brief', 'document-intake', 'ritual-booking', 'stay-enquiry', 'sales-brief', 'assessment-enquiry', 'cohort-enquiry', 'hiring-brief', 'freight-quote', 'planning-intake', 'visa-assessment', 'diagnostic-brief', 'document-appointment', 'boardroom-intake', 'commission-brief', 'project-quote', 'room-brief', 'landscape-quote', 'cleaning-quote', 'maintenance-request', 'editorial-brief', 'technical-brief', 'design-brief', 'collaboration-brief', 'episode-brief', 'speaking-brief', 'coaching-fit', 'collector-enquiry', 'agency-brief', 'market-order', 'product-advice', 'showroom-visit', 'routine-advice', 'subscription-help', 'trade-account', 'custom-order', 'venue-date-check', 'event-brief', 'trip-enquiry', 'supporter-action', 'participation-enquiry', 'visit-ministry', 'tasting-reservation', 'cafe-order', 'bar-booking', 'truck-location', 'private-dining-enquiry', 'bakery-order', 'catering-quote', 'cellar-booking', 'therapy-enquiry', 'specialist-referral', 'pet-visit-request', 'service-enquiry'],
  pricing:     ['v1', 'dining-packages', 'visit-options', 'engagement-scope', 'coaching-plans', 'grooming-packages', 'treatment-fees', 'enrolment-options', 'property-options', 'service-plans', 'collection-offers', 'creative-packages', 'advisory-retainers', 'treatment-rituals', 'room-offers', 'capacity-options', 'tutoring-packages', 'cohort-options', 'hiring-retainers', 'freight-options', 'planning-retainers', 'visa-options', 'diagnostic-packages', 'notary-fees', 'executive-retainers', 'commission-options', 'build-packages', 'design-packages', 'landscape-packages', 'cleaning-packages', 'maintenance-plans', 'editorial-packages', 'technical-retainers', 'design-engagements', 'creator-packages', 'production-packages', 'speaking-packages', 'coaching-programs', 'art-offers', 'agency-retainers', 'market-boxes', 'product-bundles', 'showroom-packages', 'routine-kits', 'box-subscriptions', 'trade-terms', 'maker-offers', 'venue-packages', 'event-packages', 'trip-options', 'donation-paths', 'membership-options', 'ministry-giving', 'tasting-offers', 'cafe-specials', 'bar-packages', 'truck-catering', 'private-room-offers', 'bakery-offers', 'catering-menus', 'cellar-memberships', 'therapy-fees', 'specialist-options', 'pet-care-plans', 'service-options'],
};

// Human-readable labels for the picker. Falls back to the variant key
// itself if not listed.
const VARIANT_LABELS = {
  hero: {
    v1: 'Classic banner',
    'split-image': 'Split image',
    'minimal-centered': 'Minimal centered',
    'gradient-mesh': 'Gradient mesh',
    'stat-band': 'Stat band',
    'editorial-split': 'Editorial cover',
    'card-stack': 'Card stack',
    'restaurant-cover': 'Restaurant cover',
    'clinic-intake': 'Clinic intake',
    'legal-brief': 'Legal brief',
    'training-sprint': 'Training sprint',
    'barber-chair': 'Barber chair',
    'dental-visit': 'Dental visit',
    'school-open-day': 'School open day',
    'property-showcase': 'Property showcase',
    'trade-dispatch': 'Trade dispatch',
    'retail-drop': 'Retail drop',
    'portfolio-wall': 'Portfolio wall',
    'finance-ledger': 'Finance ledger',
    'spa-ritual': 'Spa ritual',
    'hotel-stay': 'Hotel stay',
    'industrial-capability': 'Industrial capability',
    'tutor-plan': 'Tutor plan',
    'course-launchpad': 'Course launchpad',
    'recruitment-desk': 'Recruitment desk',
    'logistics-network': 'Logistics network',
    'advisor-plan': 'Advisor plan',
    'visa-pathway': 'Visa pathway',
    'diagnostic-room': 'Diagnostic room',
    'notary-counter': 'Notary counter',
    'boardroom-brief': 'Boardroom brief',
    'architecture-studio': 'Architecture studio',
    'builder-site': 'Builder site',
    'interior-lookbook': 'Interior lookbook',
    'landscape-plan': 'Landscape plan',
    'cleaning-route': 'Cleaning route',
    'maintenance-log': 'Maintenance log',
    'editorial-desk': 'Editorial desk',
    'developer-console': 'Developer console',
    'design-casefile': 'Design casefile',
    'creator-studio': 'Creator studio',
    'podcast-studio': 'Podcast studio',
    'speaker-stage': 'Speaker stage',
    'coach-authority': 'Coach authority',
    'artist-collection': 'Artist collection',
    'agency-casebook': 'Agency casebook',
    'market-stall': 'Market stall',
    'spec-catalog': 'Spec catalog',
    'showroom-floor': 'Showroom floor',
    'beauty-routine': 'Beauty routine',
    'subscription-unbox': 'Subscription unbox',
    'wholesale-desk': 'Wholesale desk',
    'maker-boutique': 'Maker boutique',
    'venue-celebration': 'Venue celebration',
    'event-command': 'Event command',
    'journey-map': 'Journey map',
    'cause-impact': 'Cause impact',
    'community-welcome': 'Community welcome',
    'ministry-gathering': 'Ministry gathering',
    'chef-table': 'Chef table',
    'cafe-counter-hero': 'Cafe counter',
    'nightlife-stage': 'Nightlife stage',
    'truck-route': 'Truck route',
    'private-room': 'Private room',
    'bakery-window': 'Bakery window',
    'catering-brief': 'Catering brief',
    'cellar-door': 'Cellar door',
    'therapy-room': 'Therapy room',
    'specialist-desk': 'Specialist desk',
    'vet-visit': 'Vet visit',
    'service-front': 'Service front',
  },
  services: {
    v1: 'Cards (default)',
    masonry: 'Masonry',
    list: 'List',
    accordion: 'Accordion',
    'pricing-table': 'Pricing table',
    'bento-grid': 'Bento grid',
    'alternating-rows': 'Alternating rows',
    'menu-board': 'Menu board',
    'care-pathways': 'Care pathways',
    'practice-dossier': 'Practice dossier',
    'program-stack': 'Program stack',
    'grooming-menu': 'Grooming menu',
    'treatment-grid': 'Treatment grid',
    'learning-pathways': 'Learning pathways',
    'property-pathways': 'Property pathways',
    'trade-quote-board': 'Trade quote board',
    'collection-shelf': 'Collection shelf',
    'case-study-grid': 'Case-study grid',
    'ledger-services': 'Ledger services',
    'ritual-menu': 'Ritual menu',
    'stay-amenities': 'Stay amenities',
    'capability-matrix': 'Capability matrix',
    'subject-pathways': 'Subject pathways',
    'module-stack': 'Module stack',
    'hiring-board': 'Hiring board',
    'lane-network': 'Lane network',
    'planning-pathways': 'Planning pathways',
    'visa-stages': 'Visa stages',
    'diagnostic-offers': 'Diagnostic offers',
    'document-tasks': 'Document tasks',
    'boardroom-services': 'Boardroom services',
    'studio-commissions': 'Studio commissions',
    'build-capabilities': 'Build capabilities',
    'room-schemes': 'Room schemes',
    'outdoor-projects': 'Outdoor projects',
    'cleaning-plans': 'Cleaning plans',
    'repair-checklist': 'Repair checklist',
    'editorial-services': 'Editorial services',
    'system-builds': 'System builds',
    'design-process': 'Design process',
    'creator-offers': 'Creator offers',
    'show-production': 'Show production',
    'talk-topics': 'Talk topics',
    'coaching-paths': 'Coaching paths',
    'collection-works': 'Collection works',
    'agency-method': 'Agency method',
    'market-groups': 'Market groups',
    'spec-categories': 'Spec categories',
    'room-collections': 'Room collections',
    'routine-sets': 'Routine sets',
    'box-plans': 'Box plans',
    'trade-ranges': 'Trade ranges',
    'maker-ranges': 'Maker ranges',
    'venue-packages': 'Venue packages',
    'event-blueprint': 'Event blueprint',
    'itinerary-paths': 'Itinerary paths',
    'impact-programs': 'Impact programs',
    'community-programs': 'Community programs',
    'ministry-pathways': 'Ministry pathways',
    'tasting-menu': 'Tasting menu',
    'cafe-shelf': 'Cafe shelf',
    'bar-programs': 'Bar programs',
    'truck-menu': 'Truck menu',
    'private-dining-packages': 'Private dining packages',
    'bakery-trays': 'Bakery trays',
    'catering-packages': 'Catering packages',
    'cellar-tastings': 'Cellar tastings',
    'therapy-pathways': 'Therapy pathways',
    'specialist-care': 'Specialist care',
    'pet-care-pathways': 'Pet care pathways',
    'service-pathways': 'Service pathways',
  },
  about: {
    v1: 'Side image',
    'quote-card': 'Quote card',
    'two-col': 'Two columns',
    centered: 'Centered narrative',
    timeline: 'Timeline',
  },
  team: {
    v1: 'Avatar grid',
    mosaic: 'Mosaic',
    list: 'List',
    carousel: 'Carousel',
    spotlight: 'Spotlight lead',
  },
  testimonials: {
    v1: 'Cards',
    'quote-rail': 'Quote rail',
    'single-spotlight': 'Single spotlight',
    'dining-reviews': 'Dining reviews',
    'patient-proof': 'Patient proof',
    'client-evidence': 'Client evidence',
    'progress-proof': 'Progress proof',
    'chair-proof': 'Chair proof',
    'patient-reassurance': 'Patient reassurance',
    'family-outcomes': 'Family outcomes',
    'seller-buyer-proof': 'Seller/buyer proof',
    'local-job-proof': 'Local job proof',
    'buyer-notes': 'Buyer notes',
    'project-proof': 'Project proof',
    'finance-confidence': 'Finance confidence',
    'guest-calm-proof': 'Guest calm proof',
    'stay-reviews': 'Stay reviews',
    'operations-proof': 'Operations proof',
    'learning-outcomes': 'Learning outcomes',
    'cohort-proof': 'Cohort proof',
    'hiring-proof': 'Hiring proof',
    'delivery-proof': 'Delivery proof',
    'advisor-confidence': 'Advisor confidence',
    'visa-confidence': 'Visa confidence',
    'diagnostic-proof': 'Diagnostic proof',
    'document-proof': 'Document proof',
    'executive-proof': 'Executive proof',
    'commission-proof': 'Commission proof',
    'build-proof': 'Build proof',
    'room-proof': 'Room proof',
    'yard-proof': 'Yard proof',
    'clean-proof': 'Clean proof',
    'home-proof': 'Home proof',
    'publication-proof': 'Publication proof',
    'technical-proof': 'Technical proof',
    'design-proof': 'Design proof',
    'audience-proof': 'Audience proof',
    'listener-proof': 'Listener proof',
    'stage-proof': 'Stage proof',
    'coaching-proof': 'Coaching proof',
    'collector-proof': 'Collector proof',
    'casebook-proof': 'Casebook proof',
    'fresh-proof': 'Fresh proof',
    'buyer-support-proof': 'Buyer support proof',
    'showroom-proof': 'Showroom proof',
    'routine-proof': 'Routine proof',
    'subscriber-proof': 'Subscriber proof',
    'trade-proof': 'Trade proof',
    'maker-proof': 'Maker proof',
    'celebration-proof': 'Celebration proof',
    'event-proof': 'Event proof',
    'traveller-proof': 'Traveller proof',
    'impact-proof': 'Impact proof',
    'member-proof': 'Member proof',
    'ministry-proof': 'Ministry proof',
    'chef-proof': 'Chef proof',
    'cafe-regulars': 'Cafe regulars',
    'nightlife-proof': 'Nightlife proof',
    'street-food-proof': 'Street food proof',
    'private-event-proof': 'Private event proof',
    'bakery-proof': 'Bakery proof',
    'catering-proof': 'Catering proof',
    'cellar-proof': 'Cellar proof',
    'therapy-proof': 'Therapy proof',
    'specialist-proof': 'Specialist proof',
    'pet-family-proof': 'Pet family proof',
    'service-proof': 'Service proof',
  },
  gallery: {
    v1: 'Grid',
    mosaic: 'Mosaic',
    slideshow: 'Slideshow',
    'dining-strip': 'Dining strip',
    'clinic-tour': 'Clinic tour',
    'firm-library': 'Firm library',
    'training-floor': 'Training floor',
    'barber-lookbook': 'Barber lookbook',
    'dental-suite': 'Dental suite',
    'campus-tour': 'Campus tour',
    'property-tour': 'Property tour',
    'before-after': 'Before/after',
    'commerce-lookbook': 'Commerce lookbook',
    'portfolio-wall': 'Portfolio wall',
    'document-stack': 'Document stack',
    'ritual-atmosphere': 'Ritual atmosphere',
    'stay-gallery': 'Stay gallery',
    'factory-floor': 'Factory floor',
    'learning-space': 'Learning space',
    'course-assets': 'Course assets',
    'pipeline-board': 'Pipeline board',
    'network-map': 'Network map',
    'planning-desk': 'Planning desk',
    'visa-documents': 'Visa documents',
    'diagnostic-workshop': 'Diagnostic workshop',
    'notary-documents': 'Notary documents',
    'boardroom-table': 'Boardroom table',
    'architecture-projects': 'Architecture projects',
    'site-progress': 'Site progress',
    'interior-rooms': 'Interior rooms',
    'outdoor-before-after': 'Outdoor before/after',
    'cleaning-results': 'Cleaning results',
    'repair-log': 'Repair log',
    'editorial-clips': 'Editorial clips',
    'system-screens': 'System screens',
    'case-study-wall': 'Case-study wall',
    'channel-assets': 'Channel assets',
    'episode-library': 'Episode library',
    'stage-reel': 'Stage reel',
    'coaching-board': 'Coaching board',
    'art-collection': 'Art collection',
    'agency-casebook': 'Agency casebook',
    'market-shelves': 'Market shelves',
    'product-specs': 'Product specs',
    'showroom-rooms': 'Showroom rooms',
    'routine-shelf': 'Routine shelf',
    'box-unboxing': 'Box unboxing',
    'trade-catalog': 'Trade catalog',
    'maker-studio': 'Maker studio',
    'venue-spaces': 'Venue spaces',
    'event-production': 'Event production',
    'travel-scenes': 'Travel scenes',
    'cause-stories': 'Cause stories',
    'community-moments': 'Community moments',
    'ministry-life': 'Ministry life',
    'chef-pass': 'Chef pass',
    'cafe-display': 'Cafe display',
    'nightlife-room': 'Nightlife room',
    'truck-route-gallery': 'Truck route',
    'private-room-gallery': 'Private room',
    'bakery-case': 'Bakery case',
    'catering-spread': 'Catering spread',
    'cellar-gallery': 'Cellar gallery',
    'calm-space': 'Calm space',
    'specialist-suite': 'Specialist suite',
    'pet-clinic-tour': 'Pet clinic tour',
    'service-gallery': 'Service gallery',
  },
  faq: {
    v1: 'Accordion',
    numbered: 'Numbered list',
    'split-col': 'Two-column',
  },
  contact: {
    v1: 'Detailed card',
    'cta-bar': 'Full-width CTA',
    compact: 'Compact strip',
    'reservation-panel': 'Reservation panel',
    'appointment-panel': 'Appointment panel',
    'confidential-intake': 'Confidential intake',
    'goal-check': 'Goal check',
    'chair-booking': 'Chair booking',
    'appointment-request': 'Appointment request',
    'admissions-enquiry': 'Admissions enquiry',
    'appraisal-request': 'Appraisal request',
    'quote-dispatch': 'Quote dispatch',
    'shop-support': 'Shop support',
    'project-brief': 'Project brief',
    'document-intake': 'Document intake',
    'ritual-booking': 'Ritual booking',
    'stay-enquiry': 'Stay enquiry',
    'sales-brief': 'Sales brief',
    'assessment-enquiry': 'Assessment enquiry',
    'cohort-enquiry': 'Cohort enquiry',
    'hiring-brief': 'Hiring brief',
    'freight-quote': 'Freight quote',
    'planning-intake': 'Planning intake',
    'visa-assessment': 'Visa assessment',
    'diagnostic-brief': 'Diagnostic brief',
    'document-appointment': 'Document appointment',
    'boardroom-intake': 'Boardroom intake',
    'commission-brief': 'Commission brief',
    'project-quote': 'Project quote',
    'room-brief': 'Room brief',
    'landscape-quote': 'Landscape quote',
    'cleaning-quote': 'Cleaning quote',
    'maintenance-request': 'Maintenance request',
    'editorial-brief': 'Editorial brief',
    'technical-brief': 'Technical brief',
    'design-brief': 'Design brief',
    'collaboration-brief': 'Collaboration brief',
    'episode-brief': 'Episode brief',
    'speaking-brief': 'Speaking brief',
    'coaching-fit': 'Coaching fit',
    'collector-enquiry': 'Collector enquiry',
    'agency-brief': 'Agency brief',
    'market-order': 'Market order',
    'product-advice': 'Product advice',
    'showroom-visit': 'Showroom visit',
    'routine-advice': 'Routine advice',
    'subscription-help': 'Subscription help',
    'trade-account': 'Trade account',
    'custom-order': 'Custom order',
    'venue-date-check': 'Venue date check',
    'event-brief': 'Event brief',
    'trip-enquiry': 'Trip enquiry',
    'supporter-action': 'Supporter action',
    'participation-enquiry': 'Participation enquiry',
    'visit-ministry': 'Visit ministry',
    'tasting-reservation': 'Tasting reservation',
    'cafe-order': 'Cafe order',
    'bar-booking': 'Bar booking',
    'truck-location': 'Truck location',
    'private-dining-enquiry': 'Private dining enquiry',
    'bakery-order': 'Bakery order',
    'catering-quote': 'Catering quote',
    'cellar-booking': 'Cellar booking',
    'therapy-enquiry': 'Therapy enquiry',
    'specialist-referral': 'Specialist referral',
    'pet-visit-request': 'Pet visit request',
    'service-enquiry': 'Service enquiry',
  },
  pricing: {
    v1: 'Default',
    'dining-packages': 'Dining packages',
    'visit-options': 'Visit options',
    'engagement-scope': 'Engagement scope',
    'coaching-plans': 'Coaching plans',
    'grooming-packages': 'Grooming packages',
    'treatment-fees': 'Treatment fees',
    'enrolment-options': 'Enrolment options',
    'property-options': 'Property options',
    'service-plans': 'Service plans',
    'collection-offers': 'Collection offers',
    'creative-packages': 'Creative packages',
    'advisory-retainers': 'Advisory retainers',
    'treatment-rituals': 'Treatment rituals',
    'room-offers': 'Room offers',
    'capacity-options': 'Capacity options',
    'tutoring-packages': 'Tutoring packages',
    'cohort-options': 'Cohort options',
    'hiring-retainers': 'Hiring retainers',
    'freight-options': 'Freight options',
    'planning-retainers': 'Planning retainers',
    'visa-options': 'Visa options',
    'diagnostic-packages': 'Diagnostic packages',
    'notary-fees': 'Notary fees',
    'executive-retainers': 'Executive retainers',
    'commission-options': 'Commission options',
    'build-packages': 'Build packages',
    'design-packages': 'Design packages',
    'landscape-packages': 'Landscape packages',
    'cleaning-packages': 'Cleaning packages',
    'maintenance-plans': 'Maintenance plans',
    'editorial-packages': 'Editorial packages',
    'technical-retainers': 'Technical retainers',
    'design-engagements': 'Design engagements',
    'creator-packages': 'Creator packages',
    'production-packages': 'Production packages',
    'speaking-packages': 'Speaking packages',
    'coaching-programs': 'Coaching programs',
    'art-offers': 'Art offers',
    'agency-retainers': 'Agency retainers',
    'market-boxes': 'Market boxes',
    'product-bundles': 'Product bundles',
    'showroom-packages': 'Showroom packages',
    'routine-kits': 'Routine kits',
    'box-subscriptions': 'Box subscriptions',
    'trade-terms': 'Trade terms',
    'maker-offers': 'Maker offers',
    'venue-packages': 'Venue packages',
    'event-packages': 'Event packages',
    'trip-options': 'Trip options',
    'donation-paths': 'Donation paths',
    'membership-options': 'Membership options',
    'ministry-giving': 'Ministry giving',
    'tasting-offers': 'Tasting offers',
    'cafe-specials': 'Cafe specials',
    'bar-packages': 'Bar packages',
    'truck-catering': 'Truck catering',
    'private-room-offers': 'Private room offers',
    'bakery-offers': 'Bakery offers',
    'catering-menus': 'Catering menus',
    'cellar-memberships': 'Cellar memberships',
    'therapy-fees': 'Therapy fees',
    'specialist-options': 'Specialist options',
    'pet-care-plans': 'Pet care plans',
    'service-options': 'Service options',
  },
};

// Friendly section labels used in the override UI.
const SECTION_LABELS = {
  hero: 'Hero',
  services: 'Services',
  about: 'About',
  team: 'Team',
  testimonials: 'Testimonials',
  gallery: 'Gallery',
  faq: 'FAQ',
  contact: 'Contact',
  pricing: 'Pricing',
};

const DEFAULT_PRESET_KEY = 'classic';

// Resolve which preset is active for a subscription. Callers pass the
// raw subscription object straight from the tenant API. NULL or unknown
// designPreset → "classic" (the default, current rendering).
function resolvePreset(subscription) {
  const key = subscription?.designPreset;
  if (!key) return PRESETS_BY_KEY[DEFAULT_PRESET_KEY];
  return PRESETS_BY_KEY[key] || PRESETS_BY_KEY[DEFAULT_PRESET_KEY];
}

// Resolve the variant key for a section. Order of precedence:
//   1. Per-tenant override in subscription.sectionVariants[sectionKey]
//   2. The active preset's variants[sectionKey]
//   3. 'v1' (the universal Classic fallback)
function resolveVariant(subscription, sectionKey) {
  let overrides = null;
  if (subscription?.sectionVariants) {
    if (typeof subscription.sectionVariants === 'string') {
      try { overrides = JSON.parse(subscription.sectionVariants); } catch { overrides = null; }
    } else if (typeof subscription.sectionVariants === 'object') {
      overrides = subscription.sectionVariants;
    }
  }
  if (overrides && typeof overrides[sectionKey] === 'string' && overrides[sectionKey]) {
    return overrides[sectionKey];
  }
  const preset = resolvePreset(subscription);
  return preset.variants[sectionKey] || 'v1';
}

// Convenience: resolve every section variant at once. The page.js
// rendering loop calls this once and passes individual variants down
// to each section component.
function resolveAllVariants(subscription) {
  const preset = resolvePreset(subscription);
  let overrides = {};
  if (subscription?.sectionVariants) {
    if (typeof subscription.sectionVariants === 'string') {
      try { overrides = JSON.parse(subscription.sectionVariants) || {}; } catch { overrides = {}; }
    } else if (typeof subscription.sectionVariants === 'object') {
      overrides = subscription.sectionVariants;
    }
  }
  return { ...preset.variants, ...overrides };
}


const LAYOUT_PRESET_KEYS = LAYOUT_PRESETS.map((preset) => preset.key);
const VALID_LAYOUT_PRESETS = new Set(LAYOUT_PRESET_KEYS);
const SECTION_KEYS = new Set(Object.keys(AVAILABLE_VARIANTS));

function sanitizeSectionVariants(input) {
  if (!input || typeof input !== 'object') return {};
  const out = {};
  for (const [key, value] of Object.entries(input)) {
    if (!SECTION_KEYS.has(key)) continue;
    if (typeof value !== 'string') continue;
    const trimmed = value.trim();
    if (!trimmed) continue;
    out[key] = trimmed.slice(0, 64);
  }
  return out;
}

module.exports = {
  LAYOUT_PRESETS,
  LAYOUT_PRESET_KEYS,
  VALID_LAYOUT_PRESETS,
  SECTION_KEYS,
  AVAILABLE_VARIANTS,
  VARIANT_LABELS,
  SECTION_LABELS,
  DEFAULT_PRESET_KEY,
  resolvePreset,
  resolveVariant,
  resolveAllVariants,
  sanitizeSectionVariants,
};
