-- Rebalance pricing zones by purchasing power while preserving admin overrides.

UPDATE "PricingZone"
SET
  "multiplier" = CASE "slug"
    WHEN 'zone-1' THEN 1.0000
    WHEN 'zone-2' THEN 0.8500
    WHEN 'zone-3' THEN 0.6500
    WHEN 'zone-4' THEN 0.5000
    ELSE "multiplier"
  END,
  "updatedAt" = CURRENT_TIMESTAMP
WHERE "slug" IN ('zone-1', 'zone-2', 'zone-3', 'zone-4');

WITH country_zone_map ("countryCode", "zoneSlug") AS (
VALUES
  ('US', 'zone-1'),
  ('CA', 'zone-1'),
  ('GB', 'zone-1'),
  ('IE', 'zone-1'),
  ('AU', 'zone-1'),
  ('NZ', 'zone-1'),
  ('SG', 'zone-1'),
  ('HK', 'zone-1'),
  ('CH', 'zone-1'),
  ('NO', 'zone-1'),
  ('DK', 'zone-1'),
  ('SE', 'zone-1'),
  ('FI', 'zone-1'),
  ('NL', 'zone-1'),
  ('DE', 'zone-1'),
  ('FR', 'zone-1'),
  ('BE', 'zone-1'),
  ('AT', 'zone-1'),
  ('LU', 'zone-1'),
  ('IS', 'zone-1'),
  ('IL', 'zone-2'),
  ('AE', 'zone-1'),
  ('QA', 'zone-1'),
  ('ES', 'zone-2'),
  ('IT', 'zone-2'),
  ('PT', 'zone-2'),
  ('GR', 'zone-2'),
  ('CZ', 'zone-2'),
  ('PL', 'zone-2'),
  ('SK', 'zone-2'),
  ('SI', 'zone-2'),
  ('EE', 'zone-2'),
  ('LT', 'zone-2'),
  ('LV', 'zone-2'),
  ('CY', 'zone-2'),
  ('MT', 'zone-2'),
  ('KR', 'zone-2'),
  ('JP', 'zone-2'),
  ('TW', 'zone-2'),
  ('SA', 'zone-2'),
  ('KW', 'zone-2'),
  ('BH', 'zone-2'),
  ('OM', 'zone-2'),
  ('BR', 'zone-3'),
  ('MX', 'zone-3'),
  ('AR', 'zone-3'),
  ('CL', 'zone-3'),
  ('CO', 'zone-3'),
  ('PE', 'zone-3'),
  ('UY', 'zone-3'),
  ('CR', 'zone-3'),
  ('PA', 'zone-3'),
  ('ZA', 'zone-3'),
  ('TR', 'zone-3'),
  ('RO', 'zone-3'),
  ('BG', 'zone-3'),
  ('HU', 'zone-3'),
  ('HR', 'zone-3'),
  ('RS', 'zone-3'),
  ('UA', 'zone-4'),
  ('MY', 'zone-3'),
  ('TH', 'zone-3'),
  ('PH', 'zone-4'),
  ('VN', 'zone-4'),
  ('ID', 'zone-4'),
  ('CN', 'zone-3'),
  ('RU', 'zone-3'),
  ('IN', 'zone-4'),
  ('PK', 'zone-4'),
  ('BD', 'zone-4'),
  ('LK', 'zone-4'),
  ('NP', 'zone-4'),
  ('BT', 'zone-4'),
  ('MM', 'zone-4'),
  ('KH', 'zone-4'),
  ('LA', 'zone-4'),
  ('NG', 'zone-4'),
  ('KE', 'zone-4'),
  ('GH', 'zone-4'),
  ('EG', 'zone-4'),
  ('MA', 'zone-4'),
  ('TN', 'zone-4'),
  ('DZ', 'zone-3'),
  ('ET', 'zone-4'),
  ('TZ', 'zone-4'),
  ('UG', 'zone-4'),
  ('RW', 'zone-4'),
  ('SN', 'zone-4'),
  ('CI', 'zone-4'),
  ('AD', 'zone-2'),
  ('AL', 'zone-3'),
  ('BA', 'zone-3'),
  ('BY', 'zone-3'),
  ('FO', 'zone-2'),
  ('GG', 'zone-2'),
  ('GI', 'zone-2'),
  ('GL', 'zone-2'),
  ('IM', 'zone-2'),
  ('JE', 'zone-2'),
  ('LI', 'zone-2'),
  ('MC', 'zone-2'),
  ('MD', 'zone-3'),
  ('ME', 'zone-3'),
  ('MK', 'zone-3'),
  ('SM', 'zone-2'),
  ('VA', 'zone-2'),
  ('XK', 'zone-3'),
  ('AF', 'zone-4'),
  ('AM', 'zone-3'),
  ('AZ', 'zone-3'),
  ('BN', 'zone-2'),
  ('GE', 'zone-3'),
  ('IQ', 'zone-3'),
  ('IR', 'zone-3'),
  ('JO', 'zone-3'),
  ('KG', 'zone-4'),
  ('KP', 'zone-4'),
  ('KZ', 'zone-3'),
  ('LB', 'zone-4'),
  ('MN', 'zone-3'),
  ('MV', 'zone-3'),
  ('PS', 'zone-4'),
  ('SY', 'zone-4'),
  ('TJ', 'zone-4'),
  ('TL', 'zone-4'),
  ('TM', 'zone-3'),
  ('UZ', 'zone-4'),
  ('YE', 'zone-4'),
  ('AO', 'zone-4'),
  ('BF', 'zone-4'),
  ('BI', 'zone-4'),
  ('BJ', 'zone-4'),
  ('BW', 'zone-3'),
  ('CD', 'zone-4'),
  ('CF', 'zone-4'),
  ('CG', 'zone-4'),
  ('CM', 'zone-4'),
  ('CV', 'zone-4'),
  ('DJ', 'zone-4'),
  ('ER', 'zone-4'),
  ('GA', 'zone-3'),
  ('GM', 'zone-4'),
  ('GN', 'zone-4'),
  ('GQ', 'zone-3'),
  ('GW', 'zone-4'),
  ('KM', 'zone-4'),
  ('LR', 'zone-4'),
  ('LS', 'zone-4'),
  ('LY', 'zone-3'),
  ('MG', 'zone-4'),
  ('ML', 'zone-4'),
  ('MR', 'zone-4'),
  ('MU', 'zone-3'),
  ('MW', 'zone-4'),
  ('MZ', 'zone-4'),
  ('NA', 'zone-3'),
  ('NE', 'zone-4'),
  ('SC', 'zone-3'),
  ('SD', 'zone-4'),
  ('SL', 'zone-4'),
  ('SO', 'zone-4'),
  ('SS', 'zone-4'),
  ('ST', 'zone-4'),
  ('SZ', 'zone-4'),
  ('TD', 'zone-4'),
  ('TG', 'zone-4'),
  ('ZM', 'zone-4'),
  ('ZW', 'zone-4'),
  ('AG', 'zone-3'),
  ('AI', 'zone-3'),
  ('AW', 'zone-3'),
  ('BB', 'zone-3'),
  ('BM', 'zone-3'),
  ('BO', 'zone-3'),
  ('BS', 'zone-3'),
  ('BZ', 'zone-3'),
  ('CU', 'zone-3'),
  ('CW', 'zone-3'),
  ('DM', 'zone-3'),
  ('DO', 'zone-3'),
  ('EC', 'zone-3'),
  ('FK', 'zone-3'),
  ('GD', 'zone-3'),
  ('GF', 'zone-3'),
  ('GP', 'zone-3'),
  ('GT', 'zone-3'),
  ('GY', 'zone-3'),
  ('HN', 'zone-4'),
  ('HT', 'zone-4'),
  ('JM', 'zone-3'),
  ('KN', 'zone-3'),
  ('KY', 'zone-3'),
  ('LC', 'zone-3'),
  ('MQ', 'zone-3'),
  ('MS', 'zone-3'),
  ('NI', 'zone-4'),
  ('PR', 'zone-3'),
  ('PY', 'zone-3'),
  ('SR', 'zone-3'),
  ('SV', 'zone-3'),
  ('TC', 'zone-3'),
  ('TT', 'zone-3'),
  ('VC', 'zone-3'),
  ('VE', 'zone-4'),
  ('VG', 'zone-3'),
  ('VI', 'zone-3'),
  ('AS', 'zone-3'),
  ('CK', 'zone-3'),
  ('FJ', 'zone-3'),
  ('FM', 'zone-4'),
  ('GU', 'zone-3'),
  ('KI', 'zone-4'),
  ('MH', 'zone-4'),
  ('MP', 'zone-3'),
  ('NC', 'zone-3'),
  ('NR', 'zone-3'),
  ('NU', 'zone-4'),
  ('PF', 'zone-3'),
  ('PG', 'zone-4'),
  ('PW', 'zone-3'),
  ('SB', 'zone-4'),
  ('TO', 'zone-4'),
  ('TV', 'zone-4'),
  ('VU', 'zone-4'),
  ('WF', 'zone-4'),
  ('WS', 'zone-4')
),
resolved_zones AS (
  SELECT
    country_zone_map."countryCode",
    "PricingZone"."id" AS "zoneId"
  FROM country_zone_map
  INNER JOIN "PricingZone" ON "PricingZone"."slug" = country_zone_map."zoneSlug"
)
UPDATE "CountryZoneAssignment"
SET
  "zoneId" = resolved_zones."zoneId",
  "updatedAt" = CURRENT_TIMESTAMP
FROM resolved_zones
WHERE "CountryZoneAssignment"."countryCode" = resolved_zones."countryCode"
  AND "CountryZoneAssignment"."isOverride" = false
  AND "CountryZoneAssignment"."zoneId" IS DISTINCT FROM resolved_zones."zoneId";
